/**
 * Comprehensive Indian Languages Dictionary and Astrological Terminology Engine
 * Supports Hindi, Sanskrit, Gujarati, Marathi, Bengali, Tamil, Telugu, Kannada, Malayalam, Punjabi, Odia, and English.
 */

export interface IndianLanguage {
  code: string;
  name: string;
  nativeName: string;
  region: string;
  script: string;
}

export const INDIAN_LANGUAGES: IndianLanguage[] = [
  { code: 'en', name: 'English', nativeName: 'English', region: 'International', script: 'Latin' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'North / Central India', script: 'Devanagari' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', region: 'Classical Vedic', script: 'Devanagari' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'Gujarat, India', script: 'Gujarati' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'Maharashtra, India', script: 'Devanagari' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'West Bengal / Tripura', script: 'Bengali' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'Tamil Nadu, India', script: 'Tamil' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'Andhra / Telangana', script: 'Telugu' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'Karnataka, India', script: 'Kannada' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'Kerala, India', script: 'Malayalam' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'Punjab, India', script: 'Gurmukhi' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', region: 'Odisha, India', script: 'Odia' },
];

export type LanguageCode = 'en' | 'hi' | 'sa' | 'gu' | 'mr' | 'bn' | 'ta' | 'te' | 'kn' | 'ml' | 'pa' | 'or';

// Planetary translations
export const PLANET_TRANSLATIONS: Record<string, Record<LanguageCode, string>> = {
  Sun: {
    en: 'Sun (Surya)',
    hi: 'सूर्य (Surya)',
    sa: 'सूर्यः (Sūrya)',
    gu: 'સૂર્ય (Surya)',
    mr: 'सूर्य (Surya)',
    bn: 'সূর্য (Surjo)',
    ta: 'சூரியன் (Suriyan)',
    te: 'సూర్యుడు (Suryudu)',
    kn: 'ಸೂರ್ಯ (Surya)',
    ml: 'സൂര്യൻ (Sooryan)',
    pa: 'ਸੂਰਜ (Suraj)',
    or: 'ସୂର୍ଯ୍ୟ (Surya)',
  },
  Moon: {
    en: 'Moon (Chandra)',
    hi: 'चन्द्र (Chandra)',
    sa: 'चन्द्रः (Candra)',
    gu: 'ચંદ્ર (Chandra)',
    mr: 'चंद्र (Chandra)',
    bn: 'চন্দ্র (Chandro)',
    ta: 'சந்திரன் (Chandiran)',
    te: 'చంద్రుడు (Chandrudu)',
    kn: 'ಚಂದ್ರ (Chandra)',
    ml: 'ചന്ദ്രൻ (Chandran)',
    pa: 'ਚੰਨ (Chann)',
    or: 'ଚନ୍ଦ୍ର (Chandra)',
  },
  Mars: {
    en: 'Mars (Mangala)',
    hi: 'मंगल (Mangal)',
    sa: 'मङ्गलः (Maṅgala)',
    gu: 'મંગળ (Mangal)',
    mr: 'मंगळ (Mangal)',
    bn: 'মঙ্গল (Mongol)',
    ta: 'செவ்வாய் (Sevvai)',
    te: 'కుజుడు (Kujudu/Mangala)',
    kn: 'ಮಂಗಳ (Mangala)',
    ml: 'ചൊവ്വ (Chovva)',
    pa: 'ਮੰਗਲ (Mangal)',
    or: 'ମଙ୍ଗଳ (Mangala)',
  },
  Mercury: {
    en: 'Mercury (Budha)',
    hi: 'बुध (Budh)',
    sa: 'बुधः (Budha)',
    gu: 'બુધ (Budh)',
    mr: 'बुध (Budh)',
    bn: 'বুধ (Budh)',
    ta: 'புதன் (Budhan)',
    te: 'బుధుడు (Budhudu)',
    kn: 'ಬುಧ (Budha)',
    ml: 'ബുധൻ (Budhan)',
    pa: 'ਬੁੱਧ (Budh)',
    or: 'ବୁଧ (Budha)',
  },
  Jupiter: {
    en: 'Jupiter (Guru / Brihaspati)',
    hi: 'बृहस्पति / गुरु (Guru)',
    sa: 'बृहस्पतिः (Bṛhaspati)',
    gu: 'ગુરુ (Guru)',
    mr: 'गुरु (Guru)',
    bn: 'বৃহস্পতি (Brihospoti)',
    ta: 'குரு (Guru / Vyazhan)',
    te: 'గురుడు / బృహస్పతి (Guru)',
    kn: 'ಗುರು (Guru)',
    ml: 'വ്യാഴം (Vyazham / Guru)',
    pa: 'ਬ੍ਰਹਸਪਤੀ (Guru)',
    or: 'ବୃହସ୍ପତି (Guru)',
  },
  Venus: {
    en: 'Venus (Shukra)',
    hi: 'शुक्र (Shukra)',
    sa: 'शुक्रः (Śukra)',
    gu: 'શુક્ર (Shukra)',
    mr: 'शुक्र (Shukra)',
    bn: 'শুক্র (Shukro)',
    ta: 'சுக்கிரன் (Sukiran / Velli)',
    te: 'శుక్రుడు (Shukrudu)',
    kn: 'ಶುಕ್ರ (Shukra)',
    ml: 'ശുക്രൻ (Shukran / Velli)',
    pa: 'ਸ਼ੁੱਕਰ (Shukkar)',
    or: 'ଶୁକ୍ର (Shukra)',
  },
  Saturn: {
    en: 'Saturn (Shani)',
    hi: 'शनि (Shani)',
    sa: 'शनिः (Śani)',
    gu: 'શનિ (Shani)',
    mr: 'शनी (Shani)',
    bn: 'শনি (Shoni)',
    ta: 'சனி (Sani)',
    te: 'శని (Shani)',
    kn: 'ಶನಿ (Shani)',
    ml: 'ശനി (Shani)',
    pa: 'ਸ਼ਨੀ (Shani)',
    or: 'ଶନି (Shani)',
  },
  Rahu: {
    en: 'Rahu (North Node)',
    hi: 'राहु (Rahu)',
    sa: 'राहुः (Rāhu)',
    gu: 'રાહુ (Rahu)',
    mr: 'राहु (Rahu)',
    bn: 'রাহু (Rahu)',
    ta: 'ராகு (Rahu)',
    te: 'రాహువు (Rahuvu)',
    kn: 'ರಾಹು (Rahu)',
    ml: 'രാഹു (Rahu)',
    pa: 'ਰਾਹੂ (Rahu)',
    or: 'ରାହୁ (Rahu)',
  },
  Ketu: {
    en: 'Ketu (South Node)',
    hi: 'केतु (Ketu)',
    sa: 'केतुः (Ketu)',
    gu: 'કેતુ (Ketu)',
    mr: 'केतू (Ketu)',
    bn: 'কেতু (Ketu)',
    ta: 'கேது (Kethu)',
    te: 'కేతువు (Kethuvu)',
    kn: 'ಕೇತು (Ketu)',
    ml: 'കേതു (Kethu)',
    pa: 'ਕੇਤੂ (Ketu)',
    or: 'କେତୁ (Ketu)',
  },
  Uranus: {
    en: 'Uranus (Arun / Prajapati)',
    hi: 'अरुण / प्रजापति (Arun)',
    sa: 'प्रजापतिः (Prajāpati)',
    gu: 'અરુણ (Arun)',
    mr: 'हर्षल / अरुण (Arun)',
    bn: 'ইউরেনাস / প্রজাপতি (Uranus)',
    ta: 'யுரேனஸ் (Uranus)',
    te: 'వరుణుడు / యురేనస్',
    kn: 'ಯುರೇನಸ್ (Uranus)',
    ml: 'യുറാനസ് (Uranus)',
    pa: 'ਯੂਰੇਨਸ (Uranus)',
    or: 'ଅରୁଣ (Arun)',
  },
  Neptune: {
    en: 'Neptune (Varun)',
    hi: 'वरुण (Varun)',
    sa: 'वरुणः (Varuṇa)',
    gu: 'વરુણ (Varun)',
    mr: 'नेपच्यून / वरुण (Varun)',
    bn: 'নেপচুন / বরুণ (Neptune)',
    ta: 'நெப்டியூன் (Neptune)',
    te: 'నెప్ట్యూన్ / వరుణుడు',
    kn: 'ನೆಪ್ಚೂನ್ (Neptune)',
    ml: 'നെപ്റ്റ്യൂൺ (Neptune)',
    pa: 'ਨੈਪਚਿਊਨ (Neptune)',
    or: 'ବରୁଣ (Varuna)',
  },
  Pluto: {
    en: 'Pluto (Yama / Kuber)',
    hi: 'यम / प्लूटो (Yama)',
    sa: 'यमः (Yama)',
    gu: 'યમ (Yama)',
    mr: 'प्लूटो / यम (Yama)',
    bn: 'প্লুটো / যম (Pluto)',
    ta: 'புளூட்டோ (Pluto)',
    te: 'ప్లూటో / యముడు',
    kn: 'ಪ್ಲೂಟೋ (Pluto)',
    ml: 'പ്ലൂട്ടോ (Pluto)',
    pa: 'ਪਲੂਟੋ (Pluto)',
    or: 'ଯମ (Yama)',
  },
  Ascendant: {
    en: 'Ascendant (Lagna)',
    hi: 'लग्न / प्रथम भाव (Lagna)',
    sa: 'लग्नम् (Lagnam)',
    gu: 'લગ્ન (Lagna)',
    mr: 'लग्नस्थान (Lagna)',
    bn: 'লগ্ন (Lagna)',
    ta: 'லக்னம் (Lagnam)',
    te: 'లగ్నం (Lagnam)',
    kn: 'ಲಗ್ನ (Lagna)',
    ml: 'ലഗ്നം (Lagnam)',
    pa: 'ਲਗਨ (Lagna)',
    or: 'ଲଗ୍ନ (Lagna)',
  },
};

// Zodiac Sign Translations
export const SIGN_TRANSLATIONS: Record<string, Record<LanguageCode, string>> = {
  Aries: {
    en: 'Aries (Mesha)',
    hi: 'मेष (Mesh)',
    sa: 'मेषः (Meṣa)',
    gu: 'મેષ (Mesh)',
    mr: 'मेष (Mesh)',
    bn: 'মেষ (Mesh)',
    ta: 'மேஷம் (Mesham)',
    te: 'మేషం (Mesham)',
    kn: 'ಮೇಷ (Mesha)',
    ml: 'മേടം (Medam)',
    pa: 'ਮੇਖ (Mekh)',
    or: 'ମେଷ (Mesha)',
  },
  Taurus: {
    en: 'Taurus (Vrishabha)',
    hi: 'वृषभ (Vrishabh)',
    sa: 'वृषभः (Vṛṣabha)',
    gu: 'વૃષભ (Vrushabh)',
    mr: 'वृषभ (Vrushabh)',
    bn: 'বৃষ (Brisho)',
    ta: 'ரிஷபம் (Rishabam)',
    te: 'వృషభం (Vrishabham)',
    kn: 'ವೃಷಭ (Vrishabha)',
    ml: 'ഇടവം (Idavam)',
    pa: 'ਬ੍ਰਿਖ (Brikh)',
    or: 'ବୃଷଭ (Brushabha)',
  },
  Gemini: {
    en: 'Gemini (Mithuna)',
    hi: 'मिथुन (Mithun)',
    sa: 'मिथुनम् (Mithunam)',
    gu: 'મિથુન (Mithun)',
    mr: 'मिथुन (Mithun)',
    bn: 'মিথুন (Mithun)',
    ta: 'மிதுனம் (Mithunam)',
    te: 'మిథునం (Mithunam)',
    kn: 'ಮಿಥುನ (Mithuna)',
    ml: 'മിഥുനം (Mithunam)',
    pa: 'ਮਿਥੁਨ (Mithun)',
    or: 'ମିଥୁନ (Mithuna)',
  },
  Cancer: {
    en: 'Cancer (Karka)',
    hi: 'कर्क (Kark)',
    sa: 'कर्कः (Karka)',
    gu: 'કર્ક (Kark)',
    mr: 'कर्क (Kark)',
    bn: 'কর্কট (Korkot)',
    ta: 'கடகம் (Kadagam)',
    te: 'కర్కాటకం (Karkatakam)',
    kn: 'ಕರ್ಕ (Karka)',
    ml: 'കർക്കിടകം (Karkidakam)',
    pa: 'ਕਰਕ (Kark)',
    or: 'କର୍କଟ (Karkata)',
  },
  Leo: {
    en: 'Leo (Simha)',
    hi: 'सिंह (Singh)',
    sa: 'सिंहः (Siṃha)',
    gu: 'સિંહ (Sinh)',
    mr: 'सिंह (Simha)',
    bn: 'সিংহ (Singho)',
    ta: 'சிம்மம் (Simmam)',
    te: 'సింహం (Simham)',
    kn: 'ಸಿಂಹ (Simha)',
    ml: 'ചിങ്ങം (Chingam)',
    pa: 'ਸਿੰਘ (Singh)',
    or: 'ସିଂହ (Singha)',
  },
  Virgo: {
    en: 'Virgo (Kanya)',
    hi: 'कन्या (Kanya)',
    sa: 'कन्या (Kanyā)',
    gu: 'કન્યા (Kanya)',
    mr: 'कन्या (Kanya)',
    bn: 'কন্যা (Konna)',
    ta: 'கன்னி (Kanni)',
    te: 'కన్య (Kanya)',
    kn: 'ಕನ್ಯಾ (Kanya)',
    ml: 'കന്നി (Kanni)',
    pa: 'ਕੰਨਿਆ (Kanya)',
    or: 'କନ୍ୟା (Kanya)',
  },
  Libra: {
    en: 'Libra (Tula)',
    hi: 'तुला (Tula)',
    sa: 'तुला (Tulā)',
    gu: 'તુલા (Tula)',
    mr: 'तूळ (Tula)',
    bn: 'তুলা (Tula)',
    ta: 'துலாம் (Thulam)',
    te: 'తుల (Tula)',
    kn: 'ತುಲಾ (Tula)',
    ml: 'തുലാം (Thulam)',
    pa: 'ਤੁਲਾ (Tula)',
    or: 'ତୁଳା (Tula)',
  },
  Scorpio: {
    en: 'Scorpio (Vrischika)',
    hi: 'वृश्चिक (Vrishchik)',
    sa: 'वृश्चिकः (Vṛścika)',
    gu: 'વૃશ્ચિક (Vrushchik)',
    mr: 'वृश्चिक (Vrushchik)',
    bn: 'বৃশ্চিক (Brishchik)',
    ta: 'விருச்சிகம் (Viruchigam)',
    te: 'వృశ్చికం (Vrischikam)',
    kn: 'ವೃಶ್ಚಿಕ (Vrischika)',
    ml: 'വൃശ്ചികം (Vrischikam)',
    pa: 'ਬ੍ਰਿਸ਼ਚਕ (Brishchak)',
    or: 'ବିଛା / ବିଛା (Bichha)',
  },
  Sagittarius: {
    en: 'Sagittarius (Dhanu)',
    hi: 'धनु (Dhanu)',
    sa: 'धनुः (Dhanuḥ)',
    gu: 'ધન (Dhanu)',
    mr: 'धनु (Dhanu)',
    bn: 'ধনু (Dhonu)',
    ta: 'தனுசு (Dhanusu)',
    te: 'ధనుస్సు (Dhanussu)',
    kn: 'ಧನು (Dhanu)',
    ml: 'ധനു (Dhanu)',
    pa: 'ਧਨੁ (Dhanu)',
    or: 'ଧନୁ (Dhanu)',
  },
  Capricorn: {
    en: 'Capricorn (Makara)',
    hi: 'मकर (Makar)',
    sa: 'मकरः (Makara)',
    gu: 'મકર (Makar)',
    mr: 'मकर (Makar)',
    bn: 'মকর (Mokor)',
    ta: 'மகரம் (Magaram)',
    te: 'మకరం (Makaram)',
    kn: 'ಮಕರ (Makara)',
    ml: 'മകരം (Makaram)',
    pa: 'ਮਕਰ (Makar)',
    or: 'ମକର (Makara)',
  },
  Aquarius: {
    en: 'Aquarius (Kumbha)',
    hi: 'कुंभ (Kumbh)',
    sa: 'कुम्भः (Kumbha)',
    gu: 'કુંભ (Kumbh)',
    mr: 'कुंभ (Kumbh)',
    bn: 'কুম্ভ (Kumbho)',
    ta: 'கும்பம் (Kumbam)',
    te: 'కుంభం (Kumbham)',
    kn: 'ಕುಂಭ (Kumbha)',
    ml: 'കുംഭം (Kumbham)',
    pa: 'ਕੁੰਭ (Kumbh)',
    or: 'କୁମ୍ଭ (Kumbha)',
  },
  Pisces: {
    en: 'Pisces (Meena)',
    hi: 'मीन (Meen)',
    sa: 'मीनः (Mīna)',
    gu: 'મીન (Meen)',
    mr: 'मीन (Meen)',
    bn: 'মীন (Meen)',
    ta: 'மீனம் (Meenam)',
    te: 'మీనం (Meenam)',
    kn: 'ಮೀನ (Meena)',
    ml: 'മീനം (Meenam)',
    pa: 'ਮੀਨ (Meen)',
    or: 'ମୀନ (Meena)',
  },
};

// Vedic Gemstone Names
export const GEMSTONE_TRANSLATIONS: Record<string, Record<LanguageCode, string>> = {
  Ruby: {
    en: 'Ruby (Manikya)',
    hi: 'माणिक्य (Manik)',
    sa: 'माणिक्यम् (Māṇikyam)',
    gu: 'માણેક (Manek)',
    mr: 'माणिक (Manik)',
    bn: 'চুনি / মাণিক্য (Chuni/Manik)',
    ta: 'மாணிக்கம் (Manikkam)',
    te: 'మాణిక్యం (Manikyam)',
    kn: 'ಮಾಣಿಕ್ಯ (Manikya)',
    ml: 'മാണിക്യം (Manikyam)',
    pa: 'ਮਾਣਕ (Maanak)',
    or: 'ମାଣିକ୍ୟ (Manikya)',
  },
  Pearl: {
    en: 'Pearl (Moti)',
    hi: 'मोती (Moti)',
    sa: 'मुक्ता (Muktā)',
    gu: 'મોતી (Moti)',
    mr: 'मोती (Moti)',
    bn: 'মুক্তা (Mukta)',
    ta: 'முத்து (Muthu)',
    te: 'ముత్యం (Muthyam)',
    kn: 'ಮುತ್ತು (Muttu)',
    ml: 'മുത്ത് (Muthu)',
    pa: 'ਮੋਤੀ (Moti)',
    or: 'ମୁକ୍ତା (Mukta)',
  },
  'Red Coral': {
    en: 'Red Coral (Moonga)',
    hi: 'मूंगा / प्रवाल (Moonga)',
    sa: 'प्रवालम् (Pravālam)',
    gu: 'પરવાળું (Parwalu)',
    mr: 'पोवळे (Povala)',
    bn: 'পলা / প্রবাল (Pola)',
    ta: 'பவழம் (Pavazham)',
    te: 'పగడం (Pagadam)',
    kn: 'ಹವಳ (Havala)',
    ml: 'പവിഴം (Pavizham)',
    pa: 'ਮੂੰਗਾ (Moonga)',
    or: 'ପୋହଳା (Pohala)',
  },
  Emerald: {
    en: 'Emerald (Panna)',
    hi: 'पन्ना / मरकत (Panna)',
    sa: 'मरकतम् (Marakatam)',
    gu: 'પન્ના (Panna)',
    mr: 'पाचू (Pachoo)',
    bn: 'পান্না (Panna)',
    ta: 'மரகதம் (Maragatham)',
    te: 'మరకతం / పచ్చ (Pachha)',
    kn: 'ಪಚ್ಚೆ (Pachhe)',
    ml: 'മരതകം (Marathakam)',
    pa: 'ਪੰਨਾ (Panna)',
    or: 'ପାନ୍ନା (Panna)',
  },
  'Yellow Sapphire': {
    en: 'Yellow Sapphire (Pukhraj)',
    hi: 'पुखराज / पुष्पराग (Pukhraj)',
    sa: 'पुष्परागम् (Puṣparāgam)',
    gu: 'પોખરાજ (Pokhraj)',
    mr: 'पुष्कराज (Pushkaraj)',
    bn: 'পোখরাজ (Pokhraj)',
    ta: 'புஷ்பராகம் (Pushparagam)',
    te: 'పుష్యరాగం (Pushyaragam)',
    kn: 'ಪುಷ್ಯರಾಗ (Pushyaraga)',
    ml: 'പുഷ്യരാഗം (Pushyaragam)',
    pa: 'ਪੁਖਰਾਜ (Pukhraj)',
    or: 'ପୋଖରାଜ (Pokharaj)',
  },
  Diamond: {
    en: 'Diamond (Heera)',
    hi: 'हीरा / वज्र (Heera)',
    sa: 'वज्रम् (Vajram)',
    gu: 'હીરો (Heero)',
    mr: 'हिरा (Hira)',
    bn: 'হীরা (Heera)',
    ta: 'வைரம் (Vairam)',
    te: 'వజ్రం (Vajram)',
    kn: 'ವಜ್ರ (Vajra)',
    ml: 'വൈരം (Vairam)',
    pa: 'ਹੀਰਾ (Heera)',
    or: 'ହୀରା (Heera)',
  },
  'Blue Sapphire': {
    en: 'Blue Sapphire (Neelam)',
    hi: 'नीलम / इन्द्रनील (Neelam)',
    sa: 'नीलमणिः (Nīlamaṇi)',
    gu: 'નીલમ (Neelam)',
    mr: 'नीलम (Neelam)',
    bn: 'নীলা (Neela)',
    ta: 'நீலக்கல்லு (Neelam)',
    te: 'నీలం (Neelam)',
    kn: 'ನೀಲಮಣಿ (Neelamani)',
    ml: 'ഇന്ദ്രനീലക്കല്ല് (Indraneelam)',
    pa: 'ਨੀਲਮ (Neelam)',
    or: 'ନୀଳମଣି (Neelamani)',
  },
  Hessonite: {
    en: 'Hessonite Garnet (Gomed)',
    hi: 'गोमेद (Gomed)',
    sa: 'गोमेदकम् (Gomedakam)',
    gu: 'ગોમેદ (Gomed)',
    mr: 'गोमेद (Gomed)',
    bn: 'গোমেদ (Gomed)',
    ta: 'கோமேதகம் (Gomedhagam)',
    te: 'గోమేధికం (Gomedhikam)',
    kn: 'ಗೋಮೇಧಿಕ (Gomedhika)',
    ml: 'ഗോമേദകം (Gomedhakam)',
    pa: 'ਗੋਮੇਦ (Gomed)',
    or: 'ଗୋମେଦ (Gomeda)',
  },
  "Cat's Eye": {
    en: "Cat's Eye (Vaidurya / Lahsunia)",
    hi: 'लहसुनिया / वैदूर्य (Lahsunia)',
    sa: 'वैदूर्यम् (Vaidūryam)',
    gu: 'લહસુનિયા (Lahsuniya)',
    mr: 'लसण्या (Lasanya)',
    bn: 'ক্যাটস আই / বৈদূর্য (Vaidurya)',
    ta: 'வைடூரியம் (Vaiduriyam)',
    te: 'వైడూర్యం (Vaiduryam)',
    kn: 'ವೈಡೂರ್ಯ (Vaidurya)',
    ml: 'വൈഡൂര്യം (Vaidooryam)',
    pa: 'ਲਹਸੁਨੀਆ (Lahsuniya)',
    or: 'ବୈଦୂର୍ଯ୍ୟ (Baidurjya)',
  },
};

// UI and Astrological Translation dictionary
export const UI_TRANSLATIONS: Record<string, Record<LanguageCode, string>> = {
  calculatorTitle: {
    en: 'Public Natal Chart Calculator (Swiss Ephemeris)',
    hi: 'जन्म कुण्डली गणना यंत्र (स्विस एफिमेरिस)',
    sa: 'वैदिक जन्मकुण्डली साधनम् (दृक्सिद्ध)',
    gu: 'સંપૂર્ણ જન્મ કુંડળી ગણતરી (સ્વિસ એફિમેરિસ)',
    mr: 'अचूक जन्म पत्रिका व कुंडली कॅल्क्युलेटर',
    bn: 'সঠিক জন্ম কুণ্ডলী ক্যালকুলেটর (স্বিস এফিমেরিস)',
    ta: 'துல்லியமான ஜாதகக் கணிப்பு (சுவிஸ் எபிமெரிஸ்)',
    te: 'ఖచ్చితమైన జాతక చక్ర గణన యంత్రం',
    kn: 'ನಿಖರವಾದ ಜನ್ಮ ಕುಂಡಲಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    ml: 'കൃത്യമായ ജാതക ഗണനയന്ത്രം (സ്വിസ്സ് എഫിമെറിസ്)',
    pa: 'ਅਸਲੀ ਜਨਮ ਕੁੰਡਲੀ ਕੈਲਕੁਲੇਟਰ',
    or: 'ସଠିକ୍ ଜନ୍ମ କୁଣ୍ଡଳୀ ଗଣନା ଯନ୍ତ୍ର',
  },
  calculatorSubtitle: {
    en: 'Calculate precise planetary positions, Ascendant, Midheaven, 12 Houses, and Vedic Gemstone prescriptions.',
    hi: 'सटीक ग्रह स्थिति, लग्न, 12 भाव, और वैदिक रत्न परामर्श की गणना करें।',
    sa: 'स्पष्ट ग्रहस्थितयः, लग्नम्, द्वादशभावाः, तथा च रत्नपरामर्शः।',
    gu: 'ચોક્કસ ગ્રહ સ્થિતિ, લગ્ન, ૧૨ ભાવો અને વૈદિક રત્ન ઉપાય ગણો.',
    mr: 'अचूक ग्रह स्थिती, लग्न, १२ भाव आणि योग्य रत्न मार्गदर्शन मिळवा.',
    bn: 'সঠিক গ্রহের অবস্থান, লগ্ন, ১২টি ভাব এবং রত্ন পরামর্শ নির্ণয় করুন।',
    ta: 'துல்லியமான கிரக நிலைகள், லக்னம், 12 பாவங்கள் மற்றும் நவரத்தின பரிகாரங்கள்.',
    te: 'ఖచ్చితమైన గ్రహ స్థితులు, లగ్నం, 12 భావాలు మరియు రత్న ధారణ సూచనలు.',
    kn: 'ನಿಖರವಾದ ಗ್ರಹ ಸ್ಥಿತಿ, ಲಗ್ನ, 12 ಭಾವಗಳು ಮತ್ತು ವೈದಿಕ ರತ್ನ ಸಲಹೆಗಳು.',
    ml: 'കൃത്യമായ ഗ്രഹനില, ലഗ്നം, 12 ഭാവങ്ങൾ, നവരത്ന നിർദ്ദേശങ്ങൾ എന്നിവ ഗണിക്കുക.',
    pa: 'ਸਹੀ ਗ੍ਰਹਿ ਸਥਿਤੀ, ਲਗਨ, 12 ਭਾਵ ਅਤੇ ਰਤਨ ਉਪਾਅ ਵੇਖੋ।',
    or: 'ସଠିକ୍ ଗ୍ରହ ସ୍ଥିତି, ଲଗ୍ନ, ୧୨ ଭାବ ଏବଂ ବୈଦିକ ରତ୍ନ ପରାମର୍ଶ ଗଣନା କରନ୍ତୁ।',
  },
  subjectName: {
    en: 'Subject Name',
    hi: 'जातक का नाम (Subject Name)',
    sa: 'जातकस्य नाम',
    gu: 'જાતકનું નામ (Subject Name)',
    mr: 'जातकाचे नाव (Subject Name)',
    bn: 'জাতকের নাম',
    ta: 'ஜாதகர் பெயர்',
    te: 'జాతకుని పేరు',
    kn: 'ಜಾತಕರ ಹೆಸರು',
    ml: 'ജാതകന്റെ പേര്',
    pa: 'ਵਿਅਕਤੀ ਦਾ ਨਾਮ',
    or: 'ଜାତକଙ୍କ ନାମ',
  },
  dateOfBirth: {
    en: 'Date of Birth',
    hi: 'जन्म तिथि (Date of Birth)',
    sa: 'जन्मदिनाङ्कः',
    gu: 'જન્મ તારીખ',
    mr: 'जन्मतारीख',
    bn: 'জন্ম তারিখ',
    ta: 'பிறந்த தேதி',
    te: 'పుట్టిన తేదీ',
    kn: 'ಹುಟ್ಟಿದ ದಿನಾಂಕ',
    ml: 'ജനന തീയതി',
    pa: 'ਜਨਮ ਮਿਤੀ',
    or: 'ଜନ୍ମ ତାରିଖ',
  },
  timeOfBirth: {
    en: 'Time of Birth (Exact)',
    hi: 'जन्म समय (सटीक)',
    sa: 'जन्मसमयः (स्पष्टः)',
    gu: 'જન્મ સમય (ચોક્કસ)',
    mr: 'जन्म वेळ (अचूक)',
    bn: 'জন্মের সঠিক সময়',
    ta: 'பிறந்த நேரம் (துல்லியமாக)',
    te: 'పుట్టిన సమయం (ఖచ్చితంగా)',
    kn: 'ಹುಟ್ಟಿದ ಸಮಯ (ನಿಖರ)',
    ml: 'ജനന സമയം (കൃത്യമായി)',
    pa: 'ਜਨਮ ਸਮਾਂ (ਸਹੀ)',
    or: 'ଜନ୍ମ ସମୟ (ସଠିକ୍)',
  },
  placeOfBirth: {
    en: 'Place of Birth (City)',
    hi: 'जन्म स्थान (शहर)',
    sa: 'जन्मस्थानम् (नगरम्)',
    gu: 'જન્મ સ્થળ (શહેર)',
    mr: 'जन्मस्थान (गाव/शहर)',
    bn: 'জন্মস্থান (শহর)',
    ta: 'பிறந்த இடம் (ஊர்/நகரம்)',
    te: 'పుట్టిన ప్రదేశం (నగరం)',
    kn: 'ಹುಟ್ಟಿದ ಸ್ಥಳ (ನಗರ)',
    ml: 'ജനിച്ച സ്ഥലം (നഗരം)',
    pa: 'ਜਨਮ ਸਥਾਨ (ਸ਼ਹਿਰ)',
    or: 'ଜନ୍ମ ସ୍ଥାନ (ସହର)',
  },
  calculateButton: {
    en: 'Calculate Ephemeris Chart',
    hi: 'जन्म कुण्डली बनाएं (Calculate Chart)',
    sa: 'कुण्डलीं निर्मातु',
    gu: 'કુંડળી ગણો (Calculate Chart)',
    mr: 'पत्रिका तयार करा (Calculate)',
    bn: 'কুণ্ডলী তৈরি করুন',
    ta: 'ஜாதகம் கணிக்கவும்',
    te: 'జాతక చక్రాన్ని లెక్కించండి',
    kn: 'ಕುಂಡಲಿ ಲೆಕ್ಕ ಹಾಕಿ',
    ml: 'ജാതകം ഗണിക്കുക',
    pa: 'ਕੁੰਡਲੀ ਬਣਾਓ',
    or: 'ଜନ୍ମ କୁଣ୍ଡଳୀ ଗଣନା କରନ୍ତୁ',
  },
  calculating: {
    en: 'Computing Swiss Ephemeris...',
    hi: 'ग्रहों की गणना हो रही है...',
    sa: 'ग्रहस्पष्टीकरणं प्रचलति...',
    gu: 'ગ્રહોની ગણતરી ચાલુ છે...',
    mr: 'अचूक ग्रहस्थिती गणत आहे...',
    bn: 'গ্রহের অবস্থান গণনা করা হচ্ছে...',
    ta: 'கிரக நிலைகள் கணிக்கப்படுகின்றன...',
    te: 'గ్రహ స్థితులు గణింపబడుతున్నాయి...',
    kn: 'ಗ್ರಹಗಳ ಲೆಕ್ಕಾಚಾರ ನಡೆಯುತ್ತಿದೆ...',
    ml: 'ഗ്രഹങ്ങൾ കണക്കാക്കുന്നു...',
    pa: 'ਕੁੰਡਲੀ ਦੀ ਗਣਨਾ ਹੋ ਰਹੀ ਹੈ...',
    or: 'ଗ୍ରହ ସ୍ଥିତି ଗଣନା ଚାଲିଛି...',
  },
  quickSamples: {
    en: 'Quick Samples',
    hi: 'त्वरित उदाहरण (Quick Samples)',
    sa: 'शीघ्रोदाहरणानि',
    gu: 'ઝડપી ઉદાહરણો',
    mr: 'नमुना प्रोफाईल',
    bn: 'দ্রুত উদাহরণ',
    ta: 'மாதிரி அமைப்புகள்',
    te: 'శీఘ్ర నమూనాలు',
    kn: 'ಮಾದರಿಗಳು',
    ml: 'മാതൃകകൾ',
    pa: 'ਨਮੂਨੇ',
    or: 'ଉଦାହରଣ',
  },
  selectLanguage: {
    en: 'Indian Language',
    hi: 'भाषा चुनें (Select Language)',
    sa: 'भाषां चिनोतु',
    gu: 'ભાષા પસંદ કરો',
    mr: 'भाषा निवडा',
    bn: 'ভাষা নির্বাচন করুন',
    ta: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    te: 'భాషను ఎంచుకోండి',
    kn: 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    ml: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    pa: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    or: 'ଭାଷା ବାଛନ୍ତୁ',
  },
  planetaryPositions: {
    en: 'Planetary Positions & Dignities',
    hi: 'ग्रह स्थिति और बल (Planetary Positions & Dignities)',
    sa: 'ग्रहस्थितयः तथा बलम्',
    gu: 'ગ્રહ સ્થિતિ અને બળ',
    mr: 'ग्रह स्थिती व ग्रहबल',
    bn: 'গ্রহের অবস্থান ও বল',
    ta: 'கிரக நிலைகளும் பலங்களும்',
    te: 'గ్రహ స్థితులు మరియు బలములు',
    kn: 'ಗ್ರಹ ಸ್ಥಿತಿಗಳು ಮತ್ತು ಬಲಗಳು',
    ml: 'ഗ്രഹ നിലകളും ബലങ്ങളും',
    pa: 'ਗ੍ਰਹਿ ਸਥਿਤੀ ਅਤੇ ਬਲ',
    or: 'ଗ୍ରହ ସ୍ଥିତି ଏବଂ ବଳ',
  },
  gemstonePrescription: {
    en: 'Jyotish Gemstone Prescription (Ratna Chikitsa)',
    hi: 'ज्योतिषीय रत्न परामर्श (रत्न चिकित्सा)',
    sa: 'ज्योतिषीय रत्नपरामर्शः (रत्नचिकित्सा)',
    gu: 'જ્યોતિષીય રત્ન ઉપાય (રત્ન ચિકિત્સા)',
    mr: 'ज्योतिषीय रत्न सल्ला (रत्न चिकित्सा)',
    bn: 'জ্যোতিষীয় রত্ন প্রেসক্রিপশন (রত্ন চিকিৎসা)',
    ta: 'ஜோதிட ரத்தினப் பரிந்துரை (ரத்ன பரிகாரம்)',
    te: 'జ్యోతిష్య రత్న ధారణ సలహా (రత్న చికిత్స)',
    kn: 'ಜ್ಯೋತಿಷ್ಯ ರತ್ನ ಸಲಹೆ (ರತ್ನ ಚಿಕಿತ್ಸೆ)',
    ml: 'ജ്യോതിഷ രത്ന നിർദ്ദേശം (രത്ന ചികിത്സ)',
    pa: 'ਜੋਤਿਸ਼ ਰਤਨ ਉਪਾਅ',
    or: 'ଜ୍ୟୋତିଷ ରତ୍ନ ପରାମର୍ଶ (ରତ୍ନ ଚିକିତ୍ସା)',
  },
  lifeStone: {
    en: 'Life Stone (Lagna Lord)',
    hi: 'जीवन रत्न (लग्नेश)',
    sa: 'जीवनरत्नम् (लग्नेशः)',
    gu: 'જીવન રત્ન (લગ્નેશ)',
    mr: 'जीवन रत्न (लग्नेश)',
    bn: 'জীবন রত্ন (লগ্নপতি)',
    ta: 'ஜீவ ரத்தினம் (லக்னாதிபதி)',
    te: 'జీవ రత్నం (లగ్నాధిపతి)',
    kn: 'ಜೀವ ರತ್ನ (ಲಗ್ನಾಧಿಪತಿ)',
    ml: 'ജീവ രത്നം (ലഗ്നാധിപൻ)',
    pa: 'ਜੀਵਨ ਰਤਨ (ਲਗਨੇਸ਼)',
    or: 'ଜୀବନ ରତ୍ନ (ଲଗ୍ନେଶ)',
  },
  luckyStone: {
    en: 'Lucky Stone (Bhagya Lord)',
    hi: 'भाग्य रत्न (नवमेश)',
    sa: 'भाrunning्यरत्नम् (भाग्येशः)',
    gu: 'ભાગ્ય રત્ન (ભાગ્યેશ)',
    mr: 'भाग्य रत्न (नवमेश)',
    bn: 'ভাগ্য রত্ন (ভাগ্যপতি)',
    ta: 'பாக்கிய ரத்தினம் (பாக்கியாதிபதி)',
    te: 'భాగ్య రత్నం (భాగ్యాధిపతి)',
    kn: 'ಭಾಗ್ಯ ರತ್ನ (ಭಾಗ್ಯಾಧಿಪತಿ)',
    ml: 'ഭാഗ്യ രത്നം (ഭാഗ്യാധിപൻ)',
    pa: 'ਭਾਗ ਰਤਨ (ਭਾਗਿਆਪਤੀ)',
    or: 'ଭାଗ୍ୟ ରତ୍ନ (ଭାଗ୍ୟେଶ)',
  },
  fortuneStone: {
    en: 'Fortune / Intellect Stone (5th Lord)',
    hi: 'संतान व विद्या रत्न (पंचमेश)',
    sa: 'विद्यारत्नम् (पञ्चमेशः)',
    gu: 'વિદ્યા અને પુણ્ય રત્ન (પંચમેશ)',
    mr: 'पुण्य व विद्या रत्न (पंचमेश)',
    bn: 'বিদ্যারত্ন (পঞ্চমপতি)',
    ta: 'புண்ணிய ரத்தினம் (பஞ்சமாதிபதி)',
    te: 'విద్యా రత్నం (పంచమాధిపతి)',
    kn: 'ವಿದ್ಯಾ ರತ್ನ (ಪಂಚಮಾಧಿಪತಿ)',
    ml: 'വിദ്യാ രത്നം (പഞ്ചമാധിപൻ)',
    pa: 'ਵਿੱਦਿਆ ਰਤਨ (ਪੰਚਮੇਸ਼)',
    or: 'ବିଦ୍ୟା ରତ୍ନ (ପଞ୍ଚମେଶ)',
  },
  prescribedWeight: {
    en: 'Prescribed Weight',
    hi: 'उचित वजन (रत्ती / कैरेट)',
    sa: 'निर्धारितभारः (रत्तिका)',
    gu: 'યોગ્ય વજન (રત્તી/કેરેટ)',
    mr: 'योग्य वजन (रत्ती/कॅरेट)',
    bn: 'উপযুক্ত ওজন (রত্তি/ক্যারেট)',
    ta: 'பரிந்துரைக்கப்பட்ட எடை (ரத்தி/காரட்)',
    te: 'సిఫార్సు చేసిన బరువు (రత్తి/క్యారెట్)',
    kn: 'ಸೂಚಿಸಿದ ತೂಕ (ರತ್ತಿ/ಕ್ಯಾರೆಟ್)',
    ml: 'നിർദ്ദേശിച്ച ഭാരം (രത്തി/കാരറ്റ്)',
    pa: 'ਸਹੀ ਭਾਰ (ਰੱਤੀ/ਕੈਰੇਟ)',
    or: 'ସଠିକ୍ ଓଜନ (ରତ୍ତି/କ୍ୟାରେଟ୍)',
  },
  recommendedMetal: {
    en: 'Recommended Metal',
    hi: 'धारण हेतु धातु',
    sa: 'धार्यधातुः',
    gu: 'ધારણ કરવાની ધાતુ',
    mr: 'वापरण्याची धातू',
    bn: 'ব্যবহার্য ধাতু',
    ta: 'பயன்படுத்த வேண்டிய உலோகம்',
    te: 'ధరించవలసిన లోహం',
    kn: 'ಧರಿಸಬೇಕಾದ ಲೋಹ',
    ml: 'ധരിക്കേണ്ട ലോഹം',
    pa: 'ਪਹਿਨਣ ਲਈ ਧਾਤੂ',
    or: 'ଧାରଣ ପାଇଁ ଧାତୁ',
  },
  auspiciousFinger: {
    en: 'Auspicious Finger',
    hi: 'धारण करने की अंगुली',
    sa: 'धार्याङ्गुलिः',
    gu: 'ધારણ કરવાની આંગળી',
    mr: 'धारण करावयाचे बोट',
    bn: 'আংটি পরার আঙুল',
    ta: 'மோதிரம் அணிய வேண்டிய விரல்',
    te: 'ధరించవలసిన వేలు',
    kn: 'ಧರಿಸಬೇಕಾದ ಬೆರಳು',
    ml: 'മോതിരം ധരിക്കേണ്ട വിരൽ',
    pa: 'ਪਹਿਨਣ ਵਾਲੀ ਉਂਗਲ',
    or: 'ଧାରଣ କରିବା ଆଙ୍ଗୁଳି',
  },
  chantMantra: {
    en: 'Activation Mantra',
    hi: 'जाप मंत्र (Graha Mantra)',
    sa: 'ग्रहबीजमन्त्रः',
    gu: 'ગ્રહ જાપ મંત્ર',
    mr: 'ग्रह बीजमंत्र',
    bn: 'গ্রহ জপ মন্ত্র',
    ta: 'கிரக மந்திரம்',
    te: 'గ్రహ జప మంత్రం',
    kn: 'ಗ್ರಹ ಜಪ ಮಂತ್ರ',
    ml: 'ഗ്രഹ മന്ത്രം',
    pa: 'ਗ੍ਰਹਿ ਮੰਤਰ',
    or: 'ଗ୍ରହ ମନ୍ତ୍ର',
  },
  saveToCRM: {
    en: 'Save Chart to Back-Office CRM',
    hi: 'कुण्डली को CRM में सुरक्षित करें',
    sa: 'कुण्डलीं कोशे संरक्षतु',
    gu: 'કુંડળીને CRM મા સાચવો',
    mr: 'कुंडली CRM मध्ये सेव्ह करा',
    bn: 'কুণ্ডলী CRM-এ সংরক্ষণ করুন',
    ta: 'ஜாதகத்தை CRM-ல் சேமிக்கவும்',
    te: 'జాతకాన్ని CRM లో భద్రపరచండి',
    kn: 'ಕುಂಡಲಿಯನ್ನು CRM ನಲ್ಲಿ ಉಳಿಸಿ',
    ml: 'ജാതകം CRM-ൽ സൂക്ഷിക്കുക',
    pa: 'ਕੁੰਡਲੀ ਨੂੰ CRM ਵਿੱਚ ਸੰਭਾਲੋ',
    or: 'କୁଣ୍ଡଳୀକୁ CRM ରେ ସଂରକ୍ଷଣ କରନ୍ତୁ',
  },
  downloadPDF: {
    en: 'Download PDF Report',
    hi: 'PDF रिपोर्ट डाउनलोड करें',
    sa: 'PDF पत्रं डाउनलोड कुर्वन्तु',
    gu: 'PDF રિપોર્ટ ડાઉનલોડ કરો',
    mr: 'PDF अहवाल डाउनलोड करा',
    bn: 'PDF রিপোর্ট ডাউনলোড করুন',
    ta: 'PDF அறிக்கையைப் பதிவிறக்கவும்',
    te: 'PDF నివేదికను డౌన్‌లోడ్ చేయండి',
    kn: 'PDF ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    ml: 'PDF റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    pa: 'PDF ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ',
    or: 'PDF ରିପୋର୍ଟ ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
  },
  printReport: {
    en: 'Print Kundali / Chart',
    hi: 'कुण्डली प्रिंट करें (Print)',
    sa: 'कुण्डलीं मुद्रयतु',
    gu: 'કુંડળી પ્રિન્ટ કરો',
    mr: 'पत्रिका प्रिंट करा',
    bn: 'কুণ্ডলী প্রিন্ট করুন',
    ta: 'ஜாதகத்தை அச்சிடுக',
    te: 'జాతకాన్ని ప్రింట్ చేయండి',
    kn: 'ಕುಂಡಲಿ ಮುದ್ರಿಸಿ',
    ml: 'ജാതകം പ്രിന്റ് ചെയ്യുക',
    pa: 'ਕੁੰਡਲੀ ਪ੍ਰਿੰਟ ਕਰੋ',
    or: 'କୁଣ୍ଡଳୀ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
  },
  direct: {
    en: 'Direct (Margi)',
    hi: 'मार्गी (Direct)',
    sa: 'मार्गी',
    gu: 'માર્ગી',
    mr: 'मार्गी',
    bn: 'মার্গী',
    ta: 'நேர்கதி (Margi)',
    te: 'ఋజుగతి (Margi)',
    kn: 'ನೇರ ಗತಿ (Margi)',
    ml: 'നേർഗതി (Margi)',
    pa: 'ਮਾਰਗੀ',
    or: 'ମାର୍ଗୀ',
  },
  retrograde: {
    en: 'Retrograde (Vakri)',
    hi: 'वक्री (Rx)',
    sa: 'वक्री (Vakrī)',
    gu: 'વક્રી (Rx)',
    mr: 'वक्री (Rx)',
    bn: 'বক্রী (Rx)',
    ta: 'வக்ரம் (Rx)',
    te: 'వక్రగతి (Rx)',
    kn: 'ವಕ್ರ ಗತಿ (Rx)',
    ml: 'വക്രഗതി (Rx)',
    pa: 'ਵਕਰੀ (Rx)',
    or: 'ବକ୍ରୀ (Rx)',
  },
  house: {
    en: 'House / Bhava',
    hi: 'भाव (House)',
    sa: 'भावः',
    gu: 'ભાવ (House)',
    mr: 'भाव / स्थान',
    bn: 'ভাব (House)',
    ta: 'பாவம் (House)',
    te: 'భావము (House)',
    kn: 'ಭಾವ (House)',
    ml: 'ഭാവം (House)',
    pa: 'ਘਰ / ਭਾਵ',
    or: 'ଭାବ (House)',
  },
  predictionsTitle: {
    en: 'Astrological Predictions & Forecast (भविष्यफल)',
    hi: 'साप्ताहिक, मासिक एवं वार्षिक भविष्यफल (Predictions)',
    sa: 'कालचक्रफलम् (साप्ताहिक-मासिक-वार्षिकफलम्)',
    gu: 'સાપ્તાહિક, માસિક અને વાર્ષિક રાશિફળ',
    mr: 'साप्ताहिक, मासिक आणि वार्षिक भविष्यफल',
    bn: 'সাপ্তাহিক, মাসিক ও বার্ষিক রাশিফল',
    ta: 'வாராந்திர, மாதாந்திர மற்றும் வருடாந்திர பலன்கள்',
    te: 'వార, మాస మరియు వార్షిక జాతక ఫలితాలు',
    kn: 'ವಾರದ, ಮಾಸಿಕ ಮತ್ತು ವಾರ್ಷಿಕ ಭವಿಷ್ಯಫಲ',
    ml: 'പ്രവചനങ്ങളും ജാതകഫലങ്ങളും (വാരാന്ത്യ/മാസിക/വാർഷിക)',
    pa: 'ਹਫ਼ਤਾਵਾਰੀ, ਮਹੀਨਾਵਾਰ ਅਤੇ ਸਾਲਾਨਾ ਭਵਿੱਖਬਾਣੀ',
    or: 'ସାପ୍ତାହିକ, ମାସିକ ଓ ବାର୍ଷିକ ରାଶିଫଳ',
  },
  predictionsSubtitle: {
    en: 'Easy-to-understand life forecasts tailored to your natal chart and planetary transits (Gochara).',
    hi: 'आपकी जन्म कुण्डली एवं गोचर के आधार पर सरल व व्यावहारिक जीवन मार्गदर्शन।',
    sa: 'गोचरग्रहस्थित्याधारितं सरलजीवनमार्गदर्शनम्।',
    gu: 'તમારી જન્મકુંડળી અને ગ્રહ ગોચર આધારિત સરળ જીવન માર્ગદર્શન.',
    mr: 'तुमच्या जन्मकुंडली व गोचर ग्रहांवर आधारित सुलभ व व्यवहारी मार्गदर्शन.',
    bn: 'আপনার জন্মছক ও গ্রহ গোচরের ওপর ভিত্তি করে সহজ জীবন পূর্বাভাস।',
    ta: 'உங்கள் ஜாதகம் மற்றும் கிரகப் பெயர்ச்சி அடிப்படையிலான எளிய பலன்கள்.',
    te: 'మీ జాతక చక్రం మరియు గ్రహ గోచారం ఆధారంగా సులభమైన జీవిత ఫలితాలు.',
    kn: 'ನಿಮ್ಮ ಜನ್ಮ ಕುಂಡಲಿ ಮತ್ತು ಗ್ರಹ ಗೋಚಾರದ ಆಧಾರದ ಸರಳ ಜೀವನ ಭವಿಷ್ಯ.',
    ml: 'നിങ്ങളുടെ ജാതകവും ഗ്രഹസ്ഥിതിയും അടിസ്ഥാനമാക്കിയുള്ള ലളിതമായ പ്രവചനം.',
    pa: 'ਤੁਹਾਡੀ ਜਨਮ ਕੁੰਡਲੀ ਅਤੇ ਗ੍ਰਹਿਆਂ ਦੇ ਗੋਚਰ ਅਨੁਸਾਰ ਸਰਲ ਜੀਵਨ ਅਗਵਾਈ।',
    or: 'ଆପଣଙ୍କ ଜନ୍ମ କୁଣ୍ଡଳୀ ଓ ଗ୍ରହ ଗୋଚର ଉପରେ ଆଧାରିତ ସରଳ ଭବିଷ୍ୟଫଳ।',
  },
  weeklyForecast: {
    en: 'Weekly Forecast (साप्ताहिक)',
    hi: 'साप्ताहिक भविष्यफल (Weekly)',
    sa: 'साप्ताहिकफलम्',
    gu: 'સાપ્તાહિક રાશિફળ',
    mr: 'साप्ताहिक भविष्य',
    bn: 'সাপ্তাহিক রাশিফল',
    ta: 'வார பலன்கள் (Weekly)',
    te: 'వార ఫలితాలు (Weekly)',
    kn: 'ವಾರದ ಭವಿಷ್ಯ (Weekly)',
    ml: 'വാരഫലം (Weekly)',
    pa: 'ਹਫ਼ਤਾਵਾਰੀ ਫਲ',
    or: 'ସାପ୍ତାହିକ ଫଳ',
  },
  monthlyForecast: {
    en: 'Monthly Forecast (मासिक)',
    hi: 'मासिक भविष्यफल (Monthly)',
    sa: 'मासिकफलम्',
    gu: 'માસિક રાશિફળ',
    mr: 'मासिक भविष्य',
    bn: 'মাসিক রাশিফল',
    ta: 'மாத பலன்கள் (Monthly)',
    te: 'మాస ఫలితాలు (Monthly)',
    kn: 'ಮಾಸಿಕ ಭವಿಷ್ಯ (Monthly)',
    ml: 'മാസഫലം (Monthly)',
    pa: 'ਮਹੀਨਾਵਾਰ ਫਲ',
    or: 'ମାସିକ ଫଳ',
  },
  yearlyForecast: {
    en: 'Yearly Forecast (वार्षिक)',
    hi: 'वार्षिक भविष्यफल (Yearly)',
    sa: 'वार्षिकफलम्',
    gu: 'વાર્ષિક રાશિફળ',
    mr: 'वार्षिक भविष्य',
    bn: 'বার্ষিক রাশিফল',
    ta: 'வருட பலன்கள் (Yearly)',
    te: 'వార్షిక ఫలితాలు (Yearly)',
    kn: 'ವಾರ್ಷಿಕ ಭವಿಷ್ಯ (Yearly)',
    ml: 'വാർഷിക ഫലം (Yearly)',
    pa: 'ਸਾਲਾਨਾ ਫਲ',
    or: 'ବାର୍ଷିକ ଫଳ',
  },
  careerAndMoney: {
    en: 'Career, Business & Finances',
    hi: 'करियर, व्यापार व धनलाभ (Career & Wealth)',
    sa: 'कार्यक्षेत्रं वित्तलाभश्च',
    gu: 'કારકિર્દી, વ્યવસાય અને આર્થિક વૃદ્ધિ',
    mr: 'नोकरी, व्यवसाय आणि धनलाभ',
    bn: 'কর্মজীবন, ব্যবসা ও অর্থভাগ্য',
    ta: 'தொழில், வியாபாரம் மற்றும் பணவரவு',
    te: 'వృత్తి, వ్యాపారం మరియు ఆర్థికాభివృద్ధి',
    kn: 'ಉದ್ಯೋಗ, ವ್ಯಾಪಾರ ಮತ್ತು ಧನಲಾಭ',
    ml: 'തൊഴിൽ, ബിസിനസ്സ്, സാമ്പത്തിക ലാഭം',
    pa: 'ਕੰਮਕਾਜ, ਵਪਾਰ ਅਤੇ ਧਨ ਲਾਭ',
    or: 'କର୍ମକ୍ଷେତ୍ର, ବ୍ୟବସାୟ ଓ ଧନଲାଭ',
  },
  loveAndFamily: {
    en: 'Love, Marriage & Family Relations',
    hi: 'प्रेम, वैवाहिक सुख व पारिवारिक संबंध',
    sa: 'स्नेहः, दाम्पत्यं पारिवारिकसुखम्',
    gu: 'પ્રેમ, દાંપત્ય જીવન અને પારિવારિક સુખ',
    mr: 'प्रेम, वैवाहिक जीवन आणि कौटुंबिक सौख्य',
    bn: 'প্রেম, বিবাহ ও পারিবারিক সম্প্রীতি',
    ta: 'அன்பு, திருமணம் மற்றும் குடும்ப உறவுகள்',
    te: 'ప్రేమ, వైవాహిక జీవితం మరియు కుటుంబ బంధాలు',
    kn: 'ಪ್ರೀತಿ, ದಾಂಪತ್ಯ ಮತ್ತು ಕುಟುಂಬ ಸಾಮರಸ್ಯ',
    ml: 'പ്രണയം, ദാമ്പത്യം, കുടുംബബന്ധങ്ങൾ',
    pa: 'ਪਿਆਰ, ਵਿਆਹ ਅਤੇ ਪਰਿਵਾਰਕ ਸਬੰਧ',
    or: 'ପ୍ରେମ, ବିବାହ ଓ ପାରିବାରିକ ସମ୍ପର୍କ',
  },
  healthAndVitality: {
    en: 'Health, Energy & Well-being',
    hi: 'स्वास्थ्य, ऊर्जा व मानसिक शांति (Health)',
    sa: 'आरोग्यं शक्तिः मानसिकशान्तिश्च',
    gu: 'આરોગ્ય, શક્તિ અને માનસિક શાંતિ',
    mr: 'आरोग्य, ऊर्जा आणि मनःशांती',
    bn: 'স্বাস্থ্য, জীবনীশক্তি ও মানসিক শান্তি',
    ta: 'உடல்நலம், புத்துணர்ச்சி மற்றும் மன அமைதி',
    te: 'ఆరోగ్యం, శక్తి మరియు మానసిక ప్రశాంతత',
    kn: 'ಆರೋಗ್ಯ, ಶಕ್ತಿ ಮತ್ತು ಮನಃಶಾಂತಿ',
    ml: 'ആരോഗ്യം, ഊർജ്ജസ്വലത, മാനസിക സുഖം',
    pa: 'ਸਿਹਤ, ਊਰਜਾ ਅਤੇ ਮਾਨਸਿਕ ਸ਼ਾਂਤੀ',
    or: 'ସ୍ୱାସ୍ଥ୍ୟ, ଶକ୍ତି ଓ ମାନସିକ ଶାନ୍ତି',
  },
  favorableActivities: {
    en: 'Favorable Activities (What is Favored)',
    hi: 'अनुकूल कार्य (इस अवधि में क्या करें)',
    sa: 'अनुकूलकार्याणि',
    gu: 'અનુકૂળ કાર્યો (આ સમયમાં શું કરવું)',
    mr: 'अनुकूल कार्ये (काय करावे)',
    bn: 'অনুকূল কাজ (কী করা ভালো)',
    ta: 'செய்ய வேண்டிய நல்ல காரியங்கள்',
    te: 'అనుకూలమైన పనులు (ఏమి చేయాలి)',
    kn: 'ಅನುಕೂಲಕರ ಕಾರ್ಯಗಳು (ಏನು ಮಾಡಬೇಕು)',
    ml: 'അനുകൂലമായ പ്രവൃത്തികൾ (ചെയ്യേണ്ടവ)',
    pa: 'ਚੰਗੇ ਕੰਮ (ਕੀ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ)',
    or: 'ଅନୁକୂଳ କାର୍ଯ୍ୟ (କଣ କରିବା ଉଚିତ)',
  },
  cautionActivities: {
    en: 'Things to Avoid & Precautions',
    hi: 'सावधानियां (क्या न करें / किससे बचें)',
    sa: 'सावधानी / वर्जनीयानि',
    gu: 'સાવચેતી (શું ન કરવું / બચવું)',
    mr: 'सावधानता (काय टाळावे)',
    bn: 'সতর্কতা (কী বর্জন করবেন)',
    ta: 'தவிர்க்க வேண்டியவை மற்றும் எச்சரிக்கைகள்',
    te: 'జాగ్రత్తలు (ఏమి చేయకూడదు)',
    kn: 'ಎಚ್ಚರಿಕೆಗಳು (ಏನು ಮಾಡಬಾರದು)',
    ml: 'ശ്രദ്ധിക്കേണ്ട കാര്യങ്ങൾ (ഒഴിവാക്കേണ്ടവ)',
    pa: 'ਸਾਵਧਾਨੀਆਂ (ਕੀ ਨਾ ਕਰੋ)',
    or: 'ସାବଧାନତା (କଣ କରିବା ଅନୁଚିତ)',
  },
  luckyElements: {
    en: 'Lucky Elements & Daily Guidance',
    hi: 'शुभ तत्व एवं दैनिक मार्गदर्शन (Lucky Elements)',
    sa: 'शुभतत्त्वानि तथा च मार्गदर्शनम्',
    gu: 'શુભ તત્વો અને માર્ગદર્શન',
    mr: 'शुभ घटक आणि मार्गदर्शन',
    bn: 'শুভ উপাদান ও দৈনিক দিকনির্দেশনা',
    ta: 'அதிர்ஷ்டக் கூறுகள் மற்றும் தினசரி வழிகாட்டல்',
    te: 'అదృష్ట అంశాలు మరియు మార్గదర్శకత్వం',
    kn: 'ಶುಭ ಅಂಶಗಳು ಮತ್ತು ಮಾರ್ಗದರ್ಶನ',
    ml: 'ഭാഗ്യ ഘടകങ്ങളും നിർദ്ദേശങ്ങളും',
    pa: 'ਸ਼ੁਭ ਤੱਤ ਅਤੇ ਰੋਜ਼ਾਨਾ ਸੇਧ',
    or: 'ଶୁଭ ଉପାଦାନ ଓ ଦୈନିକ ମାର୍ଗଦର୍ଶନ',
  },
  actionableTip: {
    en: 'Everyday Practical Advice',
    hi: 'दैनिक जीवन के लिए व्यावहारिक सुझाव',
    sa: 'व्यावहारिकः परामर्शः',
    gu: 'રોજિંદા જીવન માટે વ્યવહારુ સલાહ',
    mr: 'दैनंदिन जीवनासाठी मोलाचा सल्ला',
    bn: 'দৈনন্দিন জীবনের কার্যকরী পরামর্শ',
    ta: 'நடைமுறை வாழ்க்கைக் குறிப்பு',
    te: 'నిత్య జీవిత ఆచరణాత్మక సలహా',
    kn: 'ದೈನಂದಿನ ಜೀವನದ ಪ್ರಾಯೋಗಿಕ ಸಲಹೆ',
    ml: 'ദൈനംദിന ജീവിതത്തിനുള്ള ഉപദേശം',
    pa: 'ਰੋਜ਼ਾਨਾ ਜ਼ਿੰਦਗੀ ਲਈ ਲਾਭਦਾਇਕ ਸੁਝਾਅ',
    or: 'ଦୈନନ୍ଦିନ ଜୀବନ ପାଇଁ ବ୍ୟବହାରିକ ପରାମର୍ଶ',
  },
  astrologicalTransits: {
    en: 'Planetary Transits & House Influences (Gochara)',
    hi: 'ग्रह गोचर एवं भाव प्रभाव (Jyotish Basis)',
    sa: 'ग्रहगोचरः भावप्रभवश्च',
    gu: 'ગ્રહ ગોચર અને ભાવ પ્રભાવ',
    mr: 'ग्रह गोचर व भाव प्रभाव',
    bn: 'গ্রহ গোচর ও ভাব প্রভাব',
    ta: 'கிரகப் பெயர்ச்சி மற்றும் பாவ தாக்கங்கள்',
    te: 'గ్రహ గోచారం మరియు భావ ప్రభావాలు',
    kn: 'ಗ್ರಹ ಗೋಚಾರ ಮತ್ತು ಭಾವ ಪ್ರಭಾವಗಳು',
    ml: 'ഗ്രഹ സഞ്ചാരവും ഭാവ സ്വാധീനവും',
    pa: 'ਗ੍ਰਹਿ ਗੋਚਰ ਅਤੇ ਭਾਵ ਪ੍ਰਭਾਵ',
    or: 'ଗ୍ରହ ଗୋଚର ଓ ଭାବ ପ୍ରଭାବ',
  },
  predictionsWindowTitle: {
    en: 'Astrological Life Forecast',
    hi: 'ज्योतिषीय जीवन भविष्यफल',
    sa: 'ज्योतिषीयं जीवनभविष्यफलम्',
    gu: 'જ્યોતિષીય જીવન ભવિષ્યફળ',
    mr: 'ज्योतिषीय जीवन भविष्य',
    bn: 'জ্যোতিষ জীবন ভবিষ্যৎবাণী',
    ta: 'ஜோதிட வாழ்க்கை பலன்கள்',
    te: 'జ్యోతిష్య జీవిత ఫలితాలు',
    kn: 'ಜ್ಯೋತಿಷ್ಯ ಜೀವನ ಭವಿಷ್ಯ',
    ml: 'ജ്യോതിഷ ജീവിത ഫലങ്ങൾ',
    pa: 'ਜੋਤਿਸ਼ ਜੀਵਨ ਭਵਿੱਖਬਾਣੀ',
    or: 'ଜ୍ୟୋତିଷ ଜୀବନ ଭବିଷ୍ୟଫଳ',
  },
  dedicatedWindow: {
    en: 'Dedicated Predictions Window',
    hi: 'विस्तृत राशिफल विंडो',
    sa: 'विस्तृतभविष्यफलवातायनम्',
    gu: 'વિસ્તૃત રાશિફળ વિન્ડો',
    mr: 'सविस्तर भविष्यफल खिडकी',
    bn: 'বিস্তারিত রাশিফল উইন্ডো',
    ta: 'முழுமையான பலன்கள் சாளரம்',
    te: 'సమగ్ర ఫలితాల విండో',
    kn: 'ಸಮಗ್ರ ಭವಿಷ್ಯ ವಿಂಡೋ',
    ml: 'വിശദമായ ജാതക ഫലങ്ങൾ',
    pa: 'ਵਿਸਤ੍ਰਿਤ ਰਾਸ਼ੀਫਲ ਵਿੰਡੋ',
    or: 'ବିସ୍ତୃତ ରାଶିଫଳ ୱିଣ୍ଡୋ',
  },
  swissPrecision: {
    en: 'Swiss Ephemeris Precision',
    hi: 'स्विस एफिमेरिस सूक्ष्म गणना',
    sa: 'दृक्सिद्ध सूक्ष्मगणना',
    gu: 'સ્વિસ એફિમેરિસ ચોકસાઈ',
    mr: 'स्विस एफिमेरिस अचूक गणना',
    bn: 'স্বিস এফিমেরিস নির্ভুল গণনা',
    ta: 'சுவிஸ் எபிமெரிஸ் துல்லியம்',
    te: 'స్విస్ ఎఫిమెరిస్ ఖచ్చితత్వం',
    kn: 'ಸ್ವಿಸ್ ಎಫಿಮೆರಿಸ್ ನಿಖರತೆ',
    ml: 'സ്വിസ്സ് എഫിമെറിസ് കൃത്യത',
    pa: 'ਸਵਿਸ ਐਫਿਮੇਰਿਸ ਸ਼ੁੱਧਤਾ',
    or: 'ସ୍ୱିସ୍ ଏଫିମେରିସ୍ ନିର୍ଭୁଲ ଗଣନା',
  },
  verifiedBirthDetails: {
    en: 'Verified Birth Details & Astrological Identity',
    hi: 'प्रमाणित जन्म विवरण एवं ज्योतिषीय पहचान',
    sa: 'प्रमाणितं जन्मविवरणं ज्योतिषीयपरिचयश्च',
    gu: 'પ્રમાણિત જન્મ વિગત અને જ્યોતિષીય ઓળખ',
    mr: 'प्रमाणित जन्म माहिती व ज्योतिषीय ओळख',
    bn: 'যাচাইকৃত জন্ম বিবরণী ও জ্যোতিষ পরিচয়',
    ta: 'சரிபார்க்கப்பட்ட பிறப்பு விவரங்கள் & ஜோதிட அடையாளம்',
    te: 'ధృవీకరించబడిన జన్మ వివరాలు & జ్యోతిష్య గుర్తింపు',
    kn: 'ಪರಿಶೀಲಿಸಿದ ಜನ್ಮ ವಿವರಗಳು ಮತ್ತು ಜ್ಯೋತಿಷ್ಯ ಗುರುತು',
    ml: 'സ്ഥിരീകരിച്ച ജനന വിവരങ്ങളും ജ്യോതിഷ ഐഡന്റിറ്റിയും',
    pa: 'ਪ੍ਰਮਾਣਿਤ ਜਨਮ ਵੇਰਵੇ ਅਤੇ ਜੋਤਿਸ਼ ਪਛਾਣ',
    or: 'ପ୍ରମାଣିତ ଜନ୍ମ ବିବରଣୀ ଓ ଜ୍ୟୋତିଷ ପରିଚୟ',
  },
  currentMahadasha: {
    en: 'Current Mahadasha',
    hi: 'वर्तमान महादशा',
    sa: 'वर्तमानमहादशा',
    gu: 'વર્તમાન મહાદશા',
    mr: 'सध्याची महादशा',
    bn: 'বর্তমান মহাদশা',
    ta: 'தற்போதைய மகாதிசை',
    te: 'ప్రస్తుత మహర్దశ',
    kn: 'ಪ್ರಸ್ತುತ ಮಹಾದಶೆ',
    ml: 'നിലവിലെ മഹാദശ',
    pa: 'ਮੌਜੂਦਾ ਮਹਾਦਸ਼ਾ',
    or: 'ବର୍ତ୍ତମାନ ମହାଦଶା',
  },
  houseSystem: {
    en: 'House System',
    hi: 'भाव पद्धति',
    sa: 'भावपद्धतिः',
    gu: 'ભાવ પદ્ધતિ',
    mr: 'भाव पद्धती',
    bn: 'ভাব পদ্ধতি',
    ta: 'பாவ முறை',
    te: 'భావ పద్ధతి',
    kn: 'ಭಾವ ಪದ್ಧತಿ',
    ml: 'ഭാവ രീതി',
    pa: 'ਭਾਵ ਪ੍ਰਣਾਲੀ',
    or: 'ଭାବ ପଦ୍ଧତି',
  },
  lifeGemstone: {
    en: 'Life Gemstone',
    hi: 'भाग्यशाली जीवन रत्न',
    sa: 'भाग्यप्रदं जीवनरत्नम्',
    gu: 'જીવન રત્ન',
    mr: 'भाग्य रत्न',
    bn: 'ভাগ্য রত্ন',
    ta: 'அதிர்ஷ்ட ரத்தினம்',
    te: 'అదృష్ట రత్నం',
    kn: 'ಅದೃಷ್ಟ ರತ್ನ',
    ml: 'ഭാഗ്യ രത്നം',
    pa: 'ਜੀਵਨ ਰਤਨ',
    or: 'ଭାଗ୍ୟ ରତ୍ନ',
  },
  predictionHorizon: {
    en: 'Prediction Horizon',
    hi: 'भविष्यफल समय-सीमा',
    sa: 'कालसीमा',
    gu: 'ભવિષ્યફળ સમયગાળો',
    mr: 'भविष्य कालावधी',
    bn: 'ভবিষ্যৎবাণীর সময়কাল',
    ta: 'பலன் காலம்',
    te: 'ఫలితాల కాలం',
    kn: 'ಭವಿಷ್ಯದ ಕಾಲಾವಧಿ',
    ml: 'ഫല പ്രവചന കാലയളവ്',
    pa: 'ਭਵਿੱਖਬਾਣੀ ਸਮਾਂ-ਸੀਮਾ',
    or: 'ଭବିଷ୍ୟଫଳ ସମୟସୀମା',
  },
  weeklyForecastTab: {
    en: 'Weekly Forecast',
    hi: 'साप्ताहिक राशिफल',
    sa: 'साप्ताहिकं भविष्यफलम्',
    gu: 'સાપ્તાહિક રાશિફળ',
    mr: 'साप्ताहिक भविष्य',
    bn: 'সাপ্তাহিক রাশিফল',
    ta: 'வாராந்திர ராசிபலன்',
    te: 'వార ఫలితాలు',
    kn: 'ವಾರದ ಭವಿಷ್ಯ',
    ml: 'വാരഫലം',
    pa: 'ਹਫ਼ਤਾਵਾਰੀ ਰਾਸ਼ੀਫਲ',
    or: 'ସାପ୍ତାହିକ ରାଶିଫଳ',
  },
  monthlyOutlookTab: {
    en: 'Monthly Outlook',
    hi: 'मासिक दृष्टिकोण',
    sa: 'मासिकं भविष्यफलम्',
    gu: 'માસિક રાશિફળ',
    mr: 'मासिक भविष्य',
    bn: 'মাসিক রাশিফল',
    ta: 'மாதாந்திர ராசிபலன்',
    te: 'నెలవారీ ఫలితాలు',
    kn: 'ಮಾಸಿಕ ಭವಿಷ್ಯ',
    ml: 'മാസഫലം',
    pa: 'ਮਹੀਨਾਵਾਰ ਰਾਸ਼ੀਫਲ',
    or: 'ମାସିକ ରାଶିଫଳ',
  },
  yearlyMasterTab: {
    en: 'Yearly Master Transit',
    hi: 'वार्षिक गोचर महाफल',
    sa: 'वार्षिकं महाफलम्',
    gu: 'વાર્ષિક મહાફળ',
    mr: 'वार्षिक महाभविष्य',
    bn: 'বার্ষিক মহাফলাফল',
    ta: 'வருடாந்திர பெருந்திட்ட பலன்',
    te: 'వార్షిక మహా ఫలితాలు',
    kn: 'ವಾರ್ಷಿಕ ಮಹಾ ಭವಿಷ್ಯ',
    ml: 'വാർഷിക ഫലങ്ങൾ',
    pa: 'ਸਾਲਾਨਾ ਮਹਾਫਲ',
    or: 'ବାର୍ଷିକ ମହାଫଳ',
  },
  overallAuspiciousness: {
    en: 'Overall Auspiciousness',
    hi: 'समग्र शुभता एवं अनुकूलता',
    sa: 'समग्रशुभता',
    gu: 'સમગ્ર શુભતા',
    mr: 'एकूण शुभता',
    bn: 'সামগ্রিক শুভফল',
    ta: 'ஒட்டுமொத்த சுபத்தன்மை',
    te: 'మొత్తం శుభ ఫలితాలు',
    kn: 'ಒಟ್ಟಾರೆ ಶುಭಫಲ',
    ml: 'മൊത്തത്തിലുള്ള ശുഭാവസ്ഥ',
    pa: 'ਕੁੱਲ ਸ਼ੁਭਤਾ',
    or: 'ସାମଗ୍ରିକ ଶୁଭତ୍ୱ',
  },
  planetaryHarmony: {
    en: 'Planetary Harmony',
    hi: 'ग्रह अनुकूलता स्तर',
    sa: 'ग्रहसामञ्जस्यम्',
    gu: 'ગ્રહ અનુકૂળતા સ્તર',
    mr: 'ग्रह अनुकूलता',
    bn: 'গ্রহের সামঞ্জস্য',
    ta: 'கிரக நல்லிணக்கம்',
    te: 'గ్రహ అనుకూలత',
    kn: 'ಗ್ರಹ ಸಾಮರಸ್ಯ',
    ml: 'ഗ്രഹ പൊരുത്തം',
    pa: 'ਗ੍ਰਹਿ ਤਾਲਮੇਲ',
    or: 'ଗ୍ରହ ସାମଞ୍ଜସ୍ୟ',
  },
  strategicAction: {
    en: 'Strategic Action',
    hi: 'रणनीतिक सुझाव व मार्गदर्शन',
    sa: 'रणनीतिकपरामर्शः',
    gu: 'વ્યવહારુ માર્ગદર્શન',
    mr: 'महत्त्वाचा सल्ला',
    bn: 'কৌশলগত পরামর্শ',
    ta: 'முக்கிய ஆலோசனை',
    te: 'వ్యూహాత్మక సలహా',
    kn: 'ಕಾರ್ಯತಂತ್ರದ ಸಲಹೆ',
    ml: 'തന്ത്രപരമായ നിർദ്ദേശം',
    pa: 'ਰਣਨੀਤਕ ਸੁਝਾਅ',
    or: 'ରଣନୈତିକ ପରାମର୍ଶ',
  },
  harmonizingDirective: {
    en: 'Harmonizing Directive',
    hi: 'सद्भाव एवं सामंजस्य सूत्र',
    sa: 'सामञ्जस्यसूत्रम्',
    gu: 'સંબંધ સુધારવા માટે',
    mr: 'सुसंवाद सूत्र',
    bn: 'সম্পর্ক উন্নয়নের পরামর্শ',
    ta: 'நல்லுறவு வழிகாட்டல்',
    te: 'సామరస్య సూచన',
    kn: 'ಸಾಮರಸ್ಯದ ಸಲಹೆ',
    ml: 'പൊരുത്തപ്പെടൽ നിർദ്ദേശം',
    pa: 'ਸੁਖਾਵੇਂ ਸੰਬੰਧ ਸੁਝਾਅ',
    or: 'ସଦ୍ଭାବନା ପରାମର୍ଶ',
  },
  vitalityDirective: {
    en: 'Vitality Directive',
    hi: 'स्वास्थ्य व ऊर्जा मंत्र',
    sa: 'आरोग्यसूत्रम्',
    gu: 'આરોગ્ય અને સ્ફૂર્તિ મંત્ર',
    mr: 'आरोग्य व ऊर्जा सल्ला',
    bn: 'সুস্বাস্থ্য ও শক্তির পরামর্শ',
    ta: 'ஆரோக்கிய வழிகாட்டல்',
    te: 'ఆరోగ్య సూచన',
    kn: 'ಆರೋಗ್ಯ ಮತ್ತು ಶಕ್ತಿ ಸೂತ್ರ',
    ml: 'ആരോഗ്യ സംരക്ഷണ നിർദ്ദേശം',
    pa: 'ਤੰਦਰੁਸਤੀ ਸੁਝਾਅ',
    or: 'ସ୍ୱାସ୍ଥ୍ୟ ସୁରକ୍ଷା ପରାମର୍ଶ',
  },
  auspiciousActivities: {
    en: 'Auspicious Activities & Initiatives',
    hi: 'शुभ एवं अनुशंसित कार्य (इस अवधि में करें)',
    sa: 'शुभकार्याणि',
    gu: 'શુભ અને અનુકૂળ કાર્યો (કરો)',
    mr: 'शुभ व फायदेशीर कामे (करा)',
    bn: 'শুভ ও ফলপ্রসূ কাজ (কী করবেন)',
    ta: 'செய்ய வேண்டிய நற்காரியங்கள்',
    te: 'చేయవలసిన శుభ కార్యాలు',
    kn: 'ಮಾಡಬೇಕಾದ ಶುಭ ಕಾರ್ಯಗಳು',
    ml: 'ശുഭകരമായ കാര്യങ്ങൾ (ചെയ്യേണ്ടവ)',
    pa: 'ਸ਼ੁਭ ਅਤੇ ਲਾਭਦਾਇਕ ਕੰਮ',
    or: 'ଶୁଭ ଓ ଲାଭଦାୟକ କାର୍ଯ୍ୟ (କରନ୍ତୁ)',
  },
  planetaryCautions: {
    en: 'Planetary Cautions & Warnings',
    hi: 'ग्रह चेतावनियां एवं सावधानियां (बचें)',
    sa: 'सावधान्यः / वर्ज्यानि',
    gu: 'સાવચેતીઓ અને ચેતવણીઓ (બચો)',
    mr: 'सावधानता व दक्षता (टाळा)',
    bn: 'সতর্কতা ও অনুচিত কাজ (কী করবেন না)',
    ta: 'எச்சரிக்கைகள் & தவிர்க்க வேண்டியவை',
    te: 'తీసుకోవలసిన జాగ్రత్తలు (చేయకూడనివి)',
    kn: 'ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ವರ್ಜ್ಯಗಳು',
    ml: 'ശ്രദ്ധിക്കേണ്ട മുൻകരുതലുകൾ (ഒഴിവാക്കേണ്ടവ)',
    pa: 'ਸਾਵਧਾਨੀਆਂ ਅਤੇ ਵਰਜਿਤ ਕੰਮ',
    or: 'ସାବଧାନତା ଓ ବର୍ଜନୀୟ କାର୍ଯ୍ୟ',
  },
  vedicRemediesAndMantra: {
    en: 'Vedic Remedies, Auspicious Elements & Mantra',
    hi: 'वैदिक उपाय, शुभ तत्व एवं दैनिक महामंत्र',
    sa: 'वैदिकोपचाराः शुभतत्त्वानि मन्त्रश्च',
    gu: 'વૈદિક ઉપાય, શુભ તત્વો અને મંત્ર',
    mr: 'वैदिक उपाय, शुभ घटक आणि मंत्र',
    bn: 'বৈদিক প্রতিকার, শুভ উপাদান ও বীজমন্ত্র',
    ta: 'வேத பரிகாரங்கள், அதிர்ஷ்ட அம்சங்கள் மற்றும் மந்திரம்',
    te: 'వైదిక నివారణలు, శుభ అంశాలు మరియు మంత్రం',
    kn: 'ವೈದಿಕ ಪರಿಹಾರಗಳು, ಶುಭ ಅಂಶಗಳು ಮತ್ತು ಮಂತ್ರ',
    ml: 'വേദ പരിഹാരങ്ങൾ, ഭാഗ്യ ഘടകങ്ങൾ, മന്ത്രം',
    pa: 'ਵੈਦਿਕ ਉਪਾਅ, ਸ਼ੁਭ ਤੱਤ ਅਤੇ ਮੰਤਰ',
    or: 'ବୈଦିକ ପ୍ରତିକାର, ଶୁଭ ଉପାଦାନ ଓ ମନ୍ତ୍ର',
  },
  auspiciousDaysLabel: {
    en: 'Auspicious Days',
    hi: 'शुभ दिन / वार',
    sa: 'शुभवासरः',
    gu: 'શુભ વાર',
    mr: 'शुभ दिवस',
    bn: 'শুভ দিন / বার',
    ta: 'அதிர்ஷ்ட நாட்கள்',
    te: 'శుభ వారములు',
    kn: 'ಶುಭ ದಿನಗಳು',
    ml: 'ഭാഗ്യ ദിനങ്ങൾ',
    pa: 'ਸ਼ੁਭ ਦਿਨ',
    or: 'ଶୁଭ ଦିବସ',
  },
  auspiciousColorsLabel: {
    en: 'Auspicious Colors',
    hi: 'शुभ रंग',
    sa: 'शुभवर्णाः',
    gu: 'શુભ રંગો',
    mr: 'शुभ रंग',
    bn: 'শুভ রং',
    ta: 'அதிர்ஷ்ட நிறங்கள்',
    te: 'శుభ రంగులు',
    kn: 'ಶುಭ ಬಣ್ಣಗಳು',
    ml: 'ഭാഗ്യ നിറങ്ങൾ',
    pa: 'ਸ਼ੁਭ ਰੰਗ',
    or: 'ଶୁଭ ରଙ୍ଗ',
  },
  luckyNumbersLabel: {
    en: 'Lucky Numbers',
    hi: 'शुभ अंक',
    sa: 'शुभाङ्काः',
    gu: 'શુભ અંક',
    mr: 'शुभ अंक',
    bn: 'শুভ সংখ্যা',
    ta: 'அதிர்ஷ்ட எண்கள்',
    te: 'అదృష్ట సంఖ్యలు',
    kn: 'ಅದೃಷ್ಟ ಸಂಖ್ಯೆಗಳು',
    ml: 'ഭാഗ്യ നമ്പറുകൾ',
    pa: 'ਸ਼ੁਭ ਅੰਕ',
    or: 'ଶୁଭ ସଂଖ୍ୟା',
  },
  favorableDirectionLabel: {
    en: 'Favorable Direction',
    hi: 'शुभ दिशा',
    sa: 'शुभदिक्',
    gu: 'શુભ દિશા',
    mr: 'शुभ दिशा',
    bn: 'শুভ দিক',
    ta: 'அதிர்ஷ்ட திசை',
    te: 'శుభ దిశ',
    kn: 'ಶುಭ ದಿಕ್ಕು',
    ml: 'അനുകൂല ദിശ',
    pa: 'ਸ਼ੁਭ ਦਿਸ਼ਾ',
    or: 'ଶୁଭ ଦିଗ',
  },
  dailyVedicMantra: {
    en: 'Daily Vedic Mantra & Affirmation',
    hi: 'दैनिक वैदिक मंत्र एवं सकारात्मक संकल्प',
    sa: 'दैनिकवैदिकमन्त्रः सङ्कल्पश्च',
    gu: 'દૈનિક વૈદિક મંત્ર અને સંકલ્પ',
    mr: 'दैनंदिन वैदिक मंत्र व सकारात्मक विचार',
    bn: 'দৈনিক বৈদিক মন্ত্র ও ইতিবাচক সংকল্প',
    ta: 'தினசரி வேத மந்திரம் மற்றும் உறுதிமொழி',
    te: 'దైనందిన వైదిక మంత్రం మరియు ధ్యానం',
    kn: 'ದೈನಂದಿನ ವೈದಿಕ ಮಂತ್ರ ಮತ್ತು ಸಂಕಲ್ಪ',
    ml: 'ദൈനംദിന വേദ മന്ത്രവും ധ്യാനവും',
    pa: 'ਰੋਜ਼ਾਨਾ ਵੈਦਿਕ ਮੰਤਰ ਅਤੇ ਸੰਕਲਪ',
    or: 'ଦୈନିକ ବୈଦିକ ମନ୍ତ୍ର ଓ ସଂକଳ୍ପ',
  },
  popOutWindowBtn: {
    en: 'Pop Out Window',
    hi: 'अलग विंडो में खोलें',
    sa: 'पृथक् उद्घाटयतु',
    gu: 'અલગ વિન્ડોમાં ખોલો',
    mr: 'वेगळ्या विंडोमध्ये उघडा',
    bn: 'আলাদা উইন্ডোতে খুলুন',
    ta: 'தனி சாளரத்தில் திற',
    te: 'ప్రత్యేక విండోలో తెరువు',
    kn: 'ಪ್ರತ್ಯೇಕ ವಿಂಡೋದಲ್ಲಿ ತೆರೆಯಿರಿ',
    ml: 'പുതിയ വിൻഡോയിൽ തുറക്കുക',
    pa: 'ਵੱਖਰੀ ਵਿੰਡੋ ਵਿੱਚ ਖੋਲ੍ਹੋ',
    or: 'ଅଲଗା ୱିଣ୍ଡୋରେ ଖୋଲନ୍ତୁ',
  },
  copyBtn: {
    en: 'Copy',
    hi: 'कॉपी करें',
    sa: 'प्रतिलिपिं कुरु',
    gu: 'કૉપિ કરો',
    mr: 'कॉपी करा',
    bn: 'কপি করুন',
    ta: 'நகலெடு',
    te: 'కాపీ చేయి',
    kn: 'ಕಾಪಿ ಮಾಡಿ',
    ml: 'പകർപ്പാവകാശം',
    pa: 'ਕਾਪੀ ਕਰੋ',
    or: 'କପି କରନ୍ତୁ',
  },
  copiedBtn: {
    en: 'Copied!',
    hi: 'कॉपी हो गया!',
    sa: 'प्रतिलिपिकृतम्!',
    gu: 'કૉપિ થઈ ગયું!',
    mr: 'कॉपी झाले!',
    bn: 'কপি হয়েছে!',
    ta: 'நகலெடுக்கப்பட்டது!',
    te: 'కాపీ చేయబడింది!',
    kn: 'ಕಾಪಿ ಮಾಡಲಾಗಿದೆ!',
    ml: 'പകർത്തി!',
    pa: 'ਕਾਪੀ ਹੋ ਗਿਆ!',
    or: 'କପି ହୋଇଗଲା!',
  },
  printBtn: {
    en: 'Print',
    hi: 'प्रिंट / PDF',
    sa: 'मुद्रणम्',
    gu: 'પ્રિન્ટ / PDF',
    mr: 'प्रिंट / PDF',
    bn: 'প্রিন্ট / PDF',
    ta: 'அச்சிடு / PDF',
    te: 'ప్రింట్ / PDF',
    kn: 'ಪ್ರಿಂಟ್ / PDF',
    ml: 'പ്രിന്റ് / PDF',
    pa: 'ਪ੍ਰਿੰਟ / PDF',
    or: 'ପ୍ରିଣ୍ଟ / PDF',
  },
  closeBtn: {
    en: 'Close',
    hi: 'बंद करें',
    sa: 'पिधाय',
    gu: 'બંધ કરો',
    mr: 'बंद करा',
    bn: 'বন্ধ করুন',
    ta: 'மூடு',
    te: 'మూసివేయి',
    kn: 'ಮುಚ್ಚಿ',
    ml: 'അടയ്ക്കുക',
    pa: 'ਬੰਦ ਕਰੋ',
    or: 'ବନ୍ଦ କରନ୍ତୁ',
  },
  openInNewTab: {
    en: 'Open In New Tab Window',
    hi: 'नए टैब विंडो में खोलें',
    sa: 'नवीनट्याब् मध्ये उद्घाटयतु',
    gu: 'નવા ટેબમાં ખોલો',
    mr: 'नवीन टॅबमध्ये उघडा',
    bn: 'নতুন ট্যাবে খুলুন',
    ta: 'புதிய தாவலில் திற',
    te: 'కొత్త ట్యాబ్‌లో తెరువు',
    kn: 'ಹೊಸ ಟ್ಯಾಬ್‌ನಲ್ಲಿ ತೆರೆಯಿರಿ',
    ml: 'പുതിയ ടാബിൽ തുറക്കുക',
    pa: 'ਨਵੇਂ ਟੈਬ ਵਿੱਚ ਖੋਲ੍ਹੋ',
    or: 'ନୂତନ ଟ୍ୟାବ୍‌ରେ ଖୋଲନ୍ତୁ',
  },
  ephemerisCalculationActive: {
    en: 'AstroERP Astronomical AI Ephemeris Calculations Active',
    hi: 'एस्ट्रो-ईआरपी खगोलीय एआई एफिमेरिस गणना सक्रिय',
    sa: 'खगोलीयगणना सक्रियं वर्तते',
    gu: 'ખગોળીય AI એફિમેરિસ ગણતરી સક્રિય',
    mr: 'खगोलीय AI एफिमेरिस गणना सक्रिय',
    bn: 'জ্যোতির্বৈজ্ঞানিক AI এফিমেরিস গণনা সক্রিয়',
    ta: 'வானியல் AI எபிமெரிஸ் கணிப்பு இயங்குகிறது',
    te: 'ఖగోళ AI ఎఫిమెరిస్ గణన సక్రియం',
    kn: 'ಖಗೋಳ AI ಎಫಿಮೆರಿಸ್ ಲೆಕ್ಕಾಚಾರ ಸಕ್ರಿಯವಾಗಿದೆ',
    ml: 'ജ്യോതിശാസ്ത്ര AI എഫിമെറിസ് ഗണന സജീവം',
    pa: 'ਖਗੋਲੀ AI ਐਫਿਮੇਰਿਸ ਗਣਨਾ ਸਰਗਰਮ',
    or: 'ଖଗୋଳୀୟ AI ଏଫିମେରିସ୍ ଗଣନା ସକ୍ରିୟ',
  },
  dispenseGemstone: {
    en: 'Dispense',
    hi: 'रत्न प्रदान करें',
    sa: 'रत्नं प्रयच्छतु',
    gu: 'રત્ન ઓર્ડર કરો',
    mr: 'रत्न द्या',
    bn: 'রত্ন দিন',
    ta: 'ரத்தினம் விநியோகி',
    te: 'రత్నాన్ని ఇవ్వండి',
    kn: 'ರತ್ನ ನೀಡಿ',
    ml: 'രത്നം വിതരണം ചെയ്യുക',
    pa: 'ਰਤਨ ਦਿਓ',
    or: 'ରତ୍ନ ପ୍ରଦାନ କରନ୍ତୁ',
  },
  statusOutlook: {
    en: 'Outlook',
    hi: 'दृष्टिकोण',
    sa: 'दृष्टिकोणः',
    gu: 'દ્રષ્ટિકોણ',
    mr: 'दृष्टिकोन',
    bn: 'দৃষ্টিভঙ্গি',
    ta: 'பார்வை',
    te: 'దృక్పథం',
    kn: 'ದೃಷ್ಟಿಕೋನ',
    ml: 'വീക്ഷണം',
    pa: 'ਦ੍ਰਿਸ਼ਟੀਕੋਣ',
    or: 'ଦୃଷ୍ଟିକୋଣ',
  },
  coordinates: {
    en: 'Coordinates',
    hi: 'भौगोलिक निर्देशांक',
    sa: 'अक्षांशरेखांशाः',
    gu: 'અક્ષાંશ-રેખાંશ',
    mr: 'अक्षांश-रेखांश',
    bn: 'স্থানাঙ্ক',
    ta: 'அமைவிடம்',
    te: 'అక్షాంశ రేఖాంశాలు',
    kn: 'ಅಕ್ಷಾಂಶ ರೇಖಾಂಶಗಳು',
    ml: 'സ്ഥാനങ്ങൾ',
    pa: 'ਕੋਆਰਡੀਨੇਟਸ',
    or: 'ଅକ୍ଷାଂଶ ଓ ଦ୍ରାଘିମା',
  },
  statusExcellent: {
    en: 'Excellent',
    hi: 'अति उत्तम (Excellent)',
    sa: 'उत्कृष्टम्',
    gu: 'અતિ ઉત્તમ',
    mr: 'अतिउत्कृष्ट',
    bn: 'চমৎকার',
    ta: 'மிகச் சிறந்தது',
    te: 'చాలా అద్భుతం',
    kn: 'ಅತ್ಯುತ್ತಮ',
    ml: 'വളരെ മികച്ചത്',
    pa: 'ਬਹੁਤ ਵਧੀਆ',
    or: 'ଅତି ଉତ୍ତମ',
  },
  statusFavorable: {
    en: 'Favorable',
    hi: 'अनुकूल (Favorable)',
    sa: 'अनुकूलम्',
    gu: 'અનુકૂળ',
    mr: 'अनुकूल',
    bn: 'অনুকূল',
    ta: 'சாதகமானது',
    te: 'అనుకూలం',
    kn: 'ಅನುಕೂಲಕರ',
    ml: 'അനുകൂലം',
    pa: 'ਅਨੁਕੂਲ',
    or: 'ଅନୁକୂଳ',
  },
  statusSteady: {
    en: 'Steady',
    hi: 'स्थिर व संतुलित (Steady)',
    sa: 'स्थिरम्',
    gu: 'સ્થિર અને સંતુલિત',
    mr: 'स्थिर व संतुलित',
    bn: 'স্থিতিশীল ও ভারসাম্যপূর্ণ',
    ta: 'நிலையானது',
    te: 'స్థిరమైనది',
    kn: 'ಸ್ಥಿರ ಮತ್ತು ಸಮತೋಲನ',
    ml: 'സ്ഥിരതയുള്ളത്',
    pa: 'ਸਥਿਰ ਅਤੇ ਸੰਤੁਲਿਤ',
    or: 'ସ୍ଥିର ଓ ସନ୍ତୁଳିତ',
  },
  statusCaution: {
    en: 'Caution',
    hi: 'सतर्कता आवश्यक (Caution)',
    sa: 'सावधानता',
    gu: 'સાવચેતી જરૂરી',
    mr: 'दक्षता आवश्यक',
    bn: 'সতর্কতা জরুরি',
    ta: 'எச்சரிக்கை தேவை',
    te: 'జాగ్రత్త అవసరం',
    kn: 'ಎಚ್ಚರಿಕೆ ಅಗತ್ಯ',
    ml: 'ശ്രദ്ധിക്കുക',
    pa: 'ਸਾਵਧਾਨੀ ਜ਼ਰੂਰੀ',
    or: 'ସାବଧାନତା ଆବଶ୍ୟକ',
  },
};

// Days of the week translations
export const DAY_TRANSLATIONS: Record<string, Record<LanguageCode, string>> = {
  Monday: {
    en: 'Monday',
    hi: 'सोमवार',
    sa: 'सोमवासरः',
    gu: 'સોમવાર',
    mr: 'सोमवार',
    bn: 'সোমবার',
    ta: 'திங்கட்கிழமை',
    te: 'సోమవారం',
    kn: 'ಸೋಮವಾರ',
    ml: 'തിങ്കളാഴ്ച',
    pa: 'ਸੋਮਵਾਰ',
    or: 'ସୋମବାର',
  },
  Tuesday: {
    en: 'Tuesday',
    hi: 'मंगलवार',
    sa: 'मङ्गलवासरः',
    gu: 'મંગળવાર',
    mr: 'मंगळवार',
    bn: 'মঙ্গলবার',
    ta: 'செவ்வாய்க்கிழமை',
    te: 'మంగళవారం',
    kn: 'ಮಂಗಳವಾರ',
    ml: 'ചൊവ്വാഴ്ച',
    pa: 'ਮੰਗਲਵਾਰ',
    or: 'ମଙ୍ଗଳବାର',
  },
  Wednesday: {
    en: 'Wednesday',
    hi: 'बुधवार',
    sa: 'बुधवासरः',
    gu: 'બુધવાર',
    mr: 'बुधवार',
    bn: 'বুধবার',
    ta: 'புதன்கிழமை',
    te: 'బుధవారం',
    kn: 'ಬುಧವಾರ',
    ml: 'ബുധനാഴ്ച',
    pa: 'ਬੁੱਧਵਾਰ',
    or: 'ବୁଧବାର',
  },
  Thursday: {
    en: 'Thursday',
    hi: 'गुरुवार / बृहस्पतिवार',
    sa: 'गुरुवासरः',
    gu: 'ગુરુવાર',
    mr: 'गुरुवार',
    bn: 'বৃহস্পতিবার',
    ta: 'வியாழக்கிழமை',
    te: 'గురువారం',
    kn: 'ಗುರುವಾರ',
    ml: 'വ്യാഴാഴ്ച',
    pa: 'ਵੀਰਵਾਰ',
    or: 'ଗୁରୁବାର',
  },
  Friday: {
    en: 'Friday',
    hi: 'शुक्रवार',
    sa: 'शुक्रवासरः',
    gu: 'શુક્રવાર',
    mr: 'शुक्रवार',
    bn: 'শুক্রবার',
    ta: 'வெள்ளிக்கிழமை',
    te: 'శుక్రవారం',
    kn: 'ಶುಕ್ರವಾರ',
    ml: 'വെള്ളിയാഴ്ച',
    pa: 'ਸ਼ੁੱਕਰਵਾਰ',
    or: 'ଶୁକ୍ରବਾਰ',
  },
  Saturday: {
    en: 'Saturday',
    hi: 'शनिवार',
    sa: 'शनिवासरः',
    gu: 'શનિવાર',
    mr: 'शनिवार',
    bn: 'শনিবার',
    ta: 'சனிக்கிழமை',
    te: 'శనివారం',
    kn: 'ಶನಿವಾರ',
    ml: 'ശനിയാഴ്ച',
    pa: 'ਸ਼ਨੀਵਾਰ',
    or: 'ଶନିବାର',
  },
  Sunday: {
    en: 'Sunday',
    hi: 'रविवार',
    sa: 'रविवासरः',
    gu: 'રવિવાર',
    mr: 'रविवार',
    bn: 'রবিবার',
    ta: 'ஞாயிற்றுக்கிழமை',
    te: 'ఆదివారం',
    kn: 'ಭಾನುವಾರ',
    ml: 'ഞായറാഴ്ച',
    pa: 'ਐਤਵਾਰ',
    or: 'ରବିବାର',
  },
};

// Direction translations
export const DIRECTION_TRANSLATIONS: Record<string, Record<LanguageCode, string>> = {
  East: {
    en: 'East (Purva)',
    hi: 'पूर्व दिशा (Purva)',
    sa: 'पूर्वदिक्',
    gu: 'પૂર્વ દિશા',
    mr: 'पूर्व दिशा',
    bn: 'পূর্ব দিক',
    ta: 'கிழக்கு திசை',
    te: 'తూర్పు దిశ',
    kn: 'ಪೂರ್ವ ದಿಕ್ಕು',
    ml: 'കിഴക്ക് ദിശ',
    pa: 'ਪੂਰਬ ਦਿਸ਼ਾ',
    or: 'ପୂର୍ବ ଦିଗ',
  },
  West: {
    en: 'West (Pashchim)',
    hi: 'पश्चिम दिशा (Pashchim)',
    sa: 'पश्चिमदिक्',
    gu: 'પશ્ચિમ દિશા',
    mr: 'पश्चिम दिशा',
    bn: 'পশ্চিম দিক',
    ta: 'மேற்கு திசை',
    te: 'పడమర దిశ',
    kn: 'ಪಶ್ಚಿಮ ದಿಕ್ಕು',
    ml: 'പടിഞ്ഞാറ് ദിശ',
    pa: 'ਪੱਛਮ ਦਿਸ਼ਾ',
    or: 'ପଶ୍ଚିମ ଦିଗ',
  },
  North: {
    en: 'North (Uttara)',
    hi: 'उत्तर दिशा (Uttara)',
    sa: 'उत्तरदिक्',
    gu: 'ઉત્તર દિશા',
    mr: 'उत्तर दिशा',
    bn: 'উত্তর দিক',
    ta: 'வடக்கு திசை',
    te: 'ఉత్తర దిశ',
    kn: 'ಉತ್ತರ ದಿಕ್ಕು',
    ml: 'വടക്ക് ദിശ',
    pa: 'ਉੱਤਰ ਦਿਸ਼ਾ',
    or: 'ଉତ୍ତର ଦିଗ',
  },
  South: {
    en: 'South (Dakshina)',
    hi: 'दक्षिण दिशा (Dakshina)',
    sa: 'दक्षिणदिक्',
    gu: 'દક્ષિણ દિશા',
    mr: 'दक्षिण दिशा',
    bn: 'দক্ষিণ দিক',
    ta: 'தெற்கு திசை',
    te: 'దక్షిణ దిశ',
    kn: 'ದಕ್ಷಿಣ ದಿಕ್ಕು',
    ml: 'തെക്ക് ദിശ',
    pa: 'ਦੱਖਣ ਦਿਸ਼ਾ',
    or: 'ଦକ୍ଷିଣ ଦିଗ',
  },
  'North-East': {
    en: 'North-East (Ishanya)',
    hi: 'ईशान कोण / उत्तर-पूर्व (Ishanya)',
    sa: 'ईशानदिक् (उत्तर-पूर्व)',
    gu: 'ઈશાન ખૂણો (ઉત્તર-પૂર્વ)',
    mr: 'ईशान्य दिशा (उत्तर-पूर्व)',
    bn: 'ঈশান কোণ (উত্তর-পূর্ব)',
    ta: 'ஈசானிய மூலை (வடகிழக்கு)',
    te: 'ఈశాన్య దిశ (ఉత్తర-తూర్పు)',
    kn: 'ಈಶಾನ್ಯ ದಿಕ್ಕು',
    ml: 'ഈശാന കോൺ (വടക്കുകിഴക്ക്)',
    pa: 'ਈਸ਼ਾਨ ਕੋਣ (ਉੱਤਰ-ਪੂਰਬ)',
    or: 'ଈଶାନ୍ୟ କୋଣ (ଉତ୍ତର-ପୂର୍ବ)',
  },
  'North-West': {
    en: 'North-West (Vayavya)',
    hi: 'वायव्य कोण / उत्तर-पश्चिम (Vayavya)',
    sa: 'वायव्यदिक्',
    gu: 'વાયવ્ય ખૂણો (ઉત્તર-પશ્ચિમ)',
    mr: 'वायव्य दिशा (उत्तर-पश्चिम)',
    bn: 'বায়ব্য কোণ (উত্তর-পশ্চিম)',
    ta: 'வாயு மூலை (வடமேற்கு)',
    te: 'వాయవ్య దిశ (ఉత్తర-పడమర)',
    kn: 'ವಾಯುವ್ಯ ದಿಕ್ಕು',
    ml: 'വായവ്യ കോൺ (വടക്കുപടിഞ്ഞാറ്)',
    pa: 'ਵਾਯਵਯ ਕੋਣ (ਉੱਤਰ-ਪੱਛਮ)',
    or: 'ବାୟବ୍ୟ କୋଣ (ଉତ୍ତର-ପଶ୍ଚିମ)',
  },
  'South-East': {
    en: 'South-East (Agneya)',
    hi: 'आग्नेय कोण / दक्षिण-पूर्व (Agneya)',
    sa: 'आग्नेयदिक्',
    gu: 'અગ્નિ ખૂણો (દક્ષિણ-પૂર્વ)',
    mr: 'આગ્નેય દિશા (દક્ષિણ-પૂર્વ)',
    bn: 'আগ্নেয় কোণ (দক্ষিণ-পূর্ব)',
    ta: 'அக்னி மூலை (தென்கிழக்கு)',
    te: 'ఆగ్నేయ దిశ (దక్షిణ-తూర్పు)',
    kn: 'ಆಗ್ನೇಯ ದಿಕ್ಕು',
    ml: 'ആഗ്നേയ കോൺ (തെക്കുകിഴക്ക്)',
    pa: 'ਅਗਨੀ ਕੋਣ (ਦੱਖਣ-ਪੂਰਬ)',
    or: 'ଆଗ୍ନେୟ କୋଣ (ଦକ୍ଷିଣ-ପୂର୍ବ)',
  },
  'South-West': {
    en: 'South-West (Nairutya)',
    hi: 'नैऋत्य कोण / दक्षिण-पश्चिम (Nairutya)',
    sa: 'नैऋत्यदिक्',
    gu: 'નૈઋત્ય ખૂણો (દક્ષિણ-પશ્ચિમ)',
    mr: 'नैऋत्य दिशा (दक्षिण-पश्चिम)',
    bn: 'নৈঋত কোণ (দক্ষিণ-পশ্চিম)',
    ta: 'நைருதி மூலை (தென்மேற்கு)',
    te: 'నైరుతి దిశ (దక్షిణ-పడమర)',
    kn: 'ನೈಋತ್ಯ ದಿಕ್ಕು',
    ml: 'നൈരൃതി കോൺ (തെക്കുപടിഞ്ഞാറ്)',
    pa: 'ਨੈਰਿਤ ਕੋਣ (ਦੱਖਣ-ਪੱਛਮ)',
    or: 'ନୈଋତ କୋଣ (ଦକ୍ଷିଣ-ପଶ୍ଚିମ)',
  },
};

// Color Translations
export const COLOR_TRANSLATIONS: Record<string, Record<LanguageCode, string>> = {
  Red: { en: 'Crimson Red', hi: 'लाल / गहरा सिंदूरी (Red)', sa: 'रक्तवर्णः', gu: 'લાલ', mr: 'लाल', bn: 'লাল', ta: 'சிவப்பு', te: 'ఎరుపు', kn: 'ಕೆಂಪು', ml: 'ചുവപ്പ്', pa: 'ਲਾਲ', or: 'ନାଲି' },
  Pink: { en: 'Rose Pink', hi: 'गुलाबी (Pink)', sa: 'पाटलवर्णः', gu: 'ગુલાબી', mr: 'ગુલાબી', bn: 'গোলাপি', ta: 'இளஞ்சிவப்பு', te: 'గులాబీ', kn: 'ಗುಲಾಬಿ', ml: 'റോസ്', pa: 'ਗੁਲਾਬੀ', or: 'ଗୋଲାପୀ' },
  Green: { en: 'Emerald Green', hi: 'हरा / पन्ना रंग (Green)', sa: 'हरिद्वर्णः', gu: 'લીલો', mr: 'हिरवा', bn: 'সবুজ', ta: 'பச்சை', te: 'ఆకుపచ్చ', kn: 'ಹಸಿರು', ml: 'പച്ച', pa: 'ਹਰਾ', or: 'ସବୁଜ' },
  White: { en: 'Pearl White', hi: 'दूधिया श्वेत / मोती रंग (White)', sa: 'श्वेतवर्णः', gu: 'શ્વેત / સફેદ', mr: 'पांढरा', bn: 'সাদা', ta: 'வெள்ளை', te: 'తెలుపు', kn: 'ಬಿಳಿ', ml: 'വെള്ള', pa: 'ਚਿੱਟਾ', or: 'ଧଳା' },
  Gold: { en: 'Royal Gold', hi: 'सुनहरा / स्वर्णिम (Gold)', sa: 'स्वर्णवर्णः', gu: 'સોનેરી', mr: 'सोनेरी', bn: 'সোনালী', ta: 'தங்க நிறம்', te: 'బంగారు రంగు', kn: 'ಚಿನ್ನದ ಬಣ್ಣ', ml: 'സ്വർണ്ണ നിറം', pa: 'ਸੁਨਹਿਰੀ', or: 'ସୁନେଲି' },
  Yellow: { en: 'Turmeric Yellow', hi: 'पीला / केसरिया (Yellow)', sa: 'पीतवर्णः', gu: 'પીળો / કેસરી', mr: 'पिवळा', bn: 'হলুদ', ta: 'மஞ்சள்', te: 'పసుపు', kn: 'ಹಳದಿ', ml: 'മഞ്ഞ', pa: 'ਪੀਲਾ', or: 'ହଳଦିଆ' },
  Blue: { en: 'Sky Blue / Navy', hi: 'नीला / आसमानी (Blue)', sa: 'नीलवर्णः', gu: 'વાદળી / નીલો', mr: 'निळा', bn: 'নীল', ta: 'நீலம்', te: 'నీలం', kn: 'ನೀಲಿ', ml: 'നീല', pa: 'ਨੀਲਾ', or: 'ନୀଳ' },
  Orange: { en: 'Saffron Orange', hi: 'नारंगी / भगवा (Orange)', sa: 'काषायवर्णः', gu: 'કેસરી / નારંગી', mr: 'केशरी', bn: 'কমলা', ta: 'ஆரஞ்சு', te: 'నారింజ', kn: 'ಕಿತ್ತಳೆ', ml: 'ഓറഞ്ച്', pa: 'ਸੰਤਰੀ', or: 'କମଳା' },
};

/**
 * Get translated text helper
 */
export function getTranslation(key: string, lang: LanguageCode | string = 'en'): string {
  const safeLang = (lang as LanguageCode) || 'en';
  if (UI_TRANSLATIONS[key] && UI_TRANSLATIONS[key][safeLang]) {
    return UI_TRANSLATIONS[key][safeLang];
  }
  if (UI_TRANSLATIONS[key] && UI_TRANSLATIONS[key]['en']) {
    return UI_TRANSLATIONS[key]['en'];
  }
  return key;
}

/**
 * Get translated Planet name
 */
export function getPlanetName(planetName: string, lang: LanguageCode | string = 'en'): string {
  const safeLang = (lang as LanguageCode) || 'en';
  if (PLANET_TRANSLATIONS[planetName] && PLANET_TRANSLATIONS[planetName][safeLang]) {
    return PLANET_TRANSLATIONS[planetName][safeLang];
  }
  return planetName;
}

/**
 * Get translated Zodiac Sign name
 */
export function getSignName(signName: string, lang: LanguageCode | string = 'en'): string {
  const safeLang = (lang as LanguageCode) || 'en';
  if (SIGN_TRANSLATIONS[signName] && SIGN_TRANSLATIONS[signName][safeLang]) {
    return SIGN_TRANSLATIONS[signName][safeLang];
  }
  return signName;
}

/**
 * Get translated Gemstone name
 */
export function getGemstoneName(gemstoneName: string, lang: LanguageCode | string = 'en'): string {
  const safeLang = (lang as LanguageCode) || 'en';
  if (GEMSTONE_TRANSLATIONS[gemstoneName] && GEMSTONE_TRANSLATIONS[gemstoneName][safeLang]) {
    return GEMSTONE_TRANSLATIONS[gemstoneName][safeLang];
  }
  return gemstoneName;
}

/**
 * Get translated Day name
 */
export function getDayName(dayName: string, lang: LanguageCode | string = 'en'): string {
  const safeLang = (lang as LanguageCode) || 'en';
  for (const day of Object.keys(DAY_TRANSLATIONS)) {
    if (dayName.includes(day)) {
      const translated = DAY_TRANSLATIONS[day][safeLang] || day;
      return dayName.replace(day, translated);
    }
  }
  return dayName;
}

/**
 * Get translated Direction name
 */
export function getDirectionName(directionText: string, lang: LanguageCode | string = 'en'): string {
  const safeLang = (lang as LanguageCode) || 'en';
  for (const [key, mapping] of Object.entries(DIRECTION_TRANSLATIONS)) {
    if (directionText.includes(key)) {
      return mapping[safeLang] || directionText;
    }
  }
  return directionText;
}

/**
 * Get translated Status name (e.g. Excellent -> अति उत्तम)
 */
export function getStatusName(status: string, lang: LanguageCode | string = 'en'): string {
  const safeLang = (lang as LanguageCode) || 'en';
  switch (status.toLowerCase()) {
    case 'excellent':
      return UI_TRANSLATIONS.statusExcellent?.[safeLang] || status;
    case 'favorable':
      return UI_TRANSLATIONS.statusFavorable?.[safeLang] || status;
    case 'steady':
      return UI_TRANSLATIONS.statusSteady?.[safeLang] || status;
    case 'caution':
      return UI_TRANSLATIONS.statusCaution?.[safeLang] || status;
    default:
      return status;
  }
}

