/**
 * Comprehensive Indian Languages Dictionary and Astrological Terminology Engine
 * Supports Hindi, Sanskrit, Gujarati, Marathi, Bengali, Tamil, Telugu, Kannada, Malayalam, Punjabi, Odia, and English.
 */

export interface IndianLanguage {
  code: string;
  name: string;
  nativeName: string;
  region: string;
  script: string;
}

export const INDIAN_LANGUAGES: IndianLanguage[] = [
  { code: 'en', name: 'English', nativeName: 'English', region: 'International', script: 'Latin' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'North / Central India', script: 'Devanagari' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', region: 'Classical Vedic', script: 'Devanagari' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'Gujarat, India', script: 'Gujarati' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'Maharashtra, India', script: 'Devanagari' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'West Bengal / Tripura', script: 'Bengali' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'Tamil Nadu, India', script: 'Tamil' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'Andhra / Telangana', script: 'Telugu' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'Karnataka, India', script: 'Kannada' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'Kerala, India', script: 'Malayalam' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'Punjab, India', script: 'Gurmukhi' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', region: 'Odisha, India', script: 'Odia' },
];

export type LanguageCode = 'en' | 'hi' | 'sa' | 'gu' | 'mr' | 'bn' | 'ta' | 'te' | 'kn' | 'ml' | 'pa' | 'or';

// Planetary translations
export const PLANET_TRANSLATIONS: Record<string, Record<LanguageCode, string>> = {
  Sun: {
    en: 'Sun (Surya)',
    hi: 'सूर्य (Surya)',
    sa: 'सूर्यः (Sūrya)',
    gu: 'સૂર્ય (Surya)',
    mr: 'सूर्य (Surya)',
    bn: 'সূর্য (Surjo)',
    ta: 'சூரியன் (Suriyan)',
    te: 'సూర్యుడు (Suryudu)',
    kn: 'ಸೂರ್ಯ (Surya)',
    ml: 'സൂര്യൻ (Sooryan)',
    pa: 'ਸੂਰਜ (Suraj)',
    or: 'ସୂର୍ଯ୍ୟ (Surya)',
  },
  Moon: {
    en: 'Moon (Chandra)',
    hi: 'चन्द्र (Chandra)',
    sa: 'चन्द्रः (Candra)',
    gu: 'ચંદ્ર (Chandra)',
    mr: 'चंद्र (Chandra)',
    bn: 'চন্দ্র (Chandro)',
    ta: 'சந்திரன் (Chandiran)',
    te: 'చంద్రుడు (Chandrudu)',
    kn: 'ಚಂದ್ರ (Chandra)',
    ml: 'ചന്ദ്രൻ (Chandran)',
    pa: 'ਚੰਨ (Chann)',
    or: 'ଚନ୍ଦ୍ର (Chandra)',
  },
  Mars: {
    en: 'Mars (Mangala)',
    hi: 'मंगल (Mangal)',
    sa: 'मङ्गलः (Maṅgala)',
    gu: 'મંગળ (Mangal)',
    mr: 'मंगळ (Mangal)',
    bn: 'মঙ্গল (Mongol)',
    ta: 'செவ்வாய் (Sevvai)',
    te: 'కుజుడు (Kujudu/Mangala)',
    kn: 'ಮಂಗಳ (Mangala)',
    ml: 'ചൊവ്വ (Chovva)',
    pa: 'ਮੰਗਲ (Mangal)',
    or: 'ମଙ୍ଗଳ (Mangala)',
  },
  Mercury: {
    en: 'Mercury (Budha)',
    hi: 'बुध (Budh)',
    sa: 'बुधः (Budha)',
    gu: 'બુધ (Budh)',
    mr: 'बुध (Budh)',
    bn: 'বুধ (Budh)',
    ta: 'புதன் (Budhan)',
    te: 'బుధుడు (Budhudu)',
    kn: 'ಬುಧ (Budha)',
    ml: 'ബുധൻ (Budhan)',
    pa: 'ਬੁੱਧ (Budh)',
    or: 'ବୁଧ (Budha)',
  },
  Jupiter: {
    en: 'Jupiter (Guru / Brihaspati)',
    hi: 'बृहस्पति / गुरु (Guru)',
    sa: 'बृहस्पतिः (Bṛhaspati)',
    gu: 'ગુરુ (Guru)',
    mr: 'गुरु (Guru)',
    bn: 'বৃহস্পতি (Brihospoti)',
    ta: 'குரு (Guru / Vyazhan)',
    te: 'గురుడు / బృహస్పతి (Guru)',
    kn: 'ಗುರು (Guru)',
    ml: 'വ്യാഴം (Vyazham / Guru)',
    pa: 'ਬ੍ਰਹਸਪਤੀ (Guru)',
    or: 'ବୃହସ୍ପତି (Guru)',
  },
  Venus: {
    en: 'Venus (Shukra)',
    hi: 'शुक्र (Shukra)',
    sa: 'शुक्रः (Śukra)',
    gu: 'શુક્ર (Shukra)',
    mr: 'शुक्र (Shukra)',
    bn: 'শুক্র (Shukro)',
    ta: 'சுக்கிரன் (Sukiran / Velli)',
    te: 'శుక్రుడు (Shukrudu)',
    kn: 'ಶುಕ್ರ (Shukra)',
    ml: 'ശുക്രൻ (Shukran / Velli)',
    pa: 'ਸ਼ੁੱਕਰ (Shukkar)',
    or: 'ଶୁକ୍ର (Shukra)',
  },
  Saturn: {
    en: 'Saturn (Shani)',
    hi: 'शनि (Shani)',
    sa: 'शनिः (Śani)',
    gu: 'શનિ (Shani)',
    mr: 'शनी (Shani)',
    bn: 'শনি (Shoni)',
    ta: 'சனி (Sani)',
    te: 'శని (Shani)',
    kn: 'ಶನಿ (Shani)',
    ml: 'ശനി (Shani)',
    pa: 'ਸ਼ਨੀ (Shani)',
    or: 'ଶନି (Shani)',
  },
  Rahu: {
    en: 'Rahu (North Node)',
    hi: 'राहु (Rahu)',
    sa: 'राहुः (Rāhu)',
    gu: 'રાહુ (Rahu)',
    mr: 'राहु (Rahu)',
    bn: 'রাহু (Rahu)',
    ta: 'ராகு (Rahu)',
    te: 'రాహువు (Rahuvu)',
    kn: 'ರಾಹು (Rahu)',
    ml: 'രാഹു (Rahu)',
    pa: 'ਰਾਹੂ (Rahu)',
    or: 'ରାହୁ (Rahu)',
  },
  Ketu: {
    en: 'Ketu (South Node)',
    hi: 'केतु (Ketu)',
    sa: 'केतुः (Ketu)',
    gu: 'કેતુ (Ketu)',
    mr: 'केतू (Ketu)',
    bn: 'কেতু (Ketu)',
    ta: 'கேது (Kethu)',
    te: 'కేతువు (Kethuvu)',
    kn: 'ಕೇತು (Ketu)',
    ml: 'കേതു (Kethu)',
    pa: 'ਕੇਤੂ (Ketu)',
    or: 'କେତୁ (Ketu)',
  },
  Uranus: {
    en: 'Uranus (Arun / Prajapati)',
    hi: 'अरुण / प्रजापति (Arun)',
    sa: 'प्रजापतिः (Prajāpati)',
    gu: 'અરુણ (Arun)',
    mr: 'हर्षल / अरुण (Arun)',
    bn: 'ইউরেনাস / প্রজাপতি (Uranus)',
    ta: 'யுரேனஸ் (Uranus)',
    te: 'వరుణుడు / యురేనస్',
    kn: 'ಯುರೇನಸ್ (Uranus)',
    ml: 'യുറാനസ് (Uranus)',
    pa: 'ਯੂਰੇਨਸ (Uranus)',
    or: 'ଅରୁଣ (Arun)',
  },
  Neptune: {
    en: 'Neptune (Varun)',
    hi: 'वरुण (Varun)',
    sa: 'वरुणः (Varuṇa)',
    gu: 'વરુણ (Varun)',
    mr: 'नेपच्यून / वरुण (Varun)',
    bn: 'নেপচুন / বরুণ (Neptune)',
    ta: 'நெப்டியூன் (Neptune)',
    te: 'నెప్ట్యూన్ / వరుణుడు',
    kn: 'ನೆಪ್ಚೂನ್ (Neptune)',
    ml: 'നെപ്റ്റ്യൂൺ (Neptune)',
    pa: 'ਨੈਪਚਿਊਨ (Neptune)',
    or: 'ବରୁଣ (Varuna)',
  },
  Pluto: {
    en: 'Pluto (Yama / Kuber)',
    hi: 'यम / प्लूटो (Yama)',
    sa: 'यमः (Yama)',
    gu: 'યમ (Yama)',
    mr: 'प्लूटो / यम (Yama)',
    bn: 'প্লুটো / যম (Pluto)',
    ta: 'புளூட்டோ (Pluto)',
    te: 'ప్లూటో / యముడు',
    kn: 'ಪ್ಲೂಟೋ (Pluto)',
    ml: 'പ്ലൂട്ടോ (Pluto)',
    pa: 'ਪਲੂਟੋ (Pluto)',
    or: 'ଯମ (Yama)',
  },
  Ascendant: {
    en: 'Ascendant (Lagna)',
    hi: 'लग्न / प्रथम भाव (Lagna)',
    sa: 'लग्नम् (Lagnam)',
    gu: 'લગ્ન (Lagna)',
    mr: 'लग्नस्थान (Lagna)',
    bn: 'লগ্ন (Lagna)',
    ta: 'லக்னம் (Lagnam)',
    te: 'లగ్నం (Lagnam)',
    kn: 'ಲಗ್ನ (Lagna)',
    ml: 'ലഗ്നം (Lagnam)',
    pa: 'ਲਗਨ (Lagna)',
    or: 'ଲଗ୍ନ (Lagna)',
  },
};

// Zodiac Sign Translations
export const SIGN_TRANSLATIONS: Record<string, Record<LanguageCode, string>> = {
  Aries: {
    en: 'Aries (Mesha)',
    hi: 'मेष (Mesh)',
    sa: 'मेषः (Meṣa)',
    gu: 'મેષ (Mesh)',
    mr: 'मेष (Mesh)',
    bn: 'মেষ (Mesh)',
    ta: 'மேஷம் (Mesham)',
    te: 'మేషం (Mesham)',
    kn: 'ಮೇಷ (Mesha)',
    ml: 'മേടം (Medam)',
    pa: 'ਮੇਖ (Mekh)',
    or: 'ମେଷ (Mesha)',
  },
  Taurus: {
    en: 'Taurus (Vrishabha)',
    hi: 'वृषभ (Vrishabh)',
    sa: 'वृषभः (Vṛṣabha)',
    gu: 'વૃષભ (Vrushabh)',
    mr: 'वृषभ (Vrushabh)',
    bn: 'বৃষ (Brisho)',
    ta: 'ரிஷபம் (Rishabam)',
    te: 'వృషభం (Vrishabham)',
    kn: 'ವೃಷಭ (Vrishabha)',
    ml: 'ഇടവം (Idavam)',
    pa: 'ਬ੍ਰਿਖ (Brikh)',
    or: 'ବୃଷଭ (Brushabha)',
  },
  Gemini: {
    en: 'Gemini (Mithuna)',
    hi: 'मिथुन (Mithun)',
    sa: 'मिथुनम् (Mithunam)',
    gu: 'મિથુન (Mithun)',
    mr: 'मिथुन (Mithun)',
    bn: 'মিথুন (Mithun)',
    ta: 'மிதுனம் (Mithunam)',
    te: 'మిథునం (Mithunam)',
    kn: 'ಮಿಥುನ (Mithuna)',
    ml: 'മിഥുനം (Mithunam)',
    pa: 'ਮਿਥੁਨ (Mithun)',
    or: 'ମିଥୁନ (Mithuna)',
  },
  Cancer: {
    en: 'Cancer (Karka)',
    hi: 'कर्क (Kark)',
    sa: 'कर्कः (Karka)',
    gu: 'કર્ક (Kark)',
    mr: 'कर्क (Kark)',
    bn: 'কর্কট (Korkot)',
    ta: 'கடகம் (Kadagam)',
    te: 'కర్కాటకం (Karkatakam)',
    kn: 'ಕರ್ಕ (Karka)',
    ml: 'കർക്കിടകം (Karkidakam)',
    pa: 'ਕਰਕ (Kark)',
    or: 'କର୍କଟ (Karkata)',
  },
  Leo: {
    en: 'Leo (Simha)',
    hi: 'सिंह (Singh)',
    sa: 'सिंहः (Siṃha)',
    gu: 'સિંહ (Sinh)',
    mr: 'सिंह (Simha)',
    bn: 'সিংহ (Singho)',
    ta: 'சிம்மம் (Simmam)',
    te: 'సింహం (Simham)',
    kn: 'ಸಿಂಹ (Simha)',
    ml: 'ചിങ്ങം (Chingam)',
    pa: 'ਸਿੰਘ (Singh)',
    or: 'ସିଂହ (Singha)',
  },
  Virgo: {
    en: 'Virgo (Kanya)',
    hi: 'कन्या (Kanya)',
    sa: 'कन्या (Kanyā)',
    gu: 'કન્યા (Kanya)',
    mr: 'कन्या (Kanya)',
    bn: 'কন্যা (Konna)',
    ta: 'கன்னி (Kanni)',
    te: 'కన్య (Kanya)',
    kn: 'ಕನ್ಯಾ (Kanya)',
    ml: 'കന്നി (Kanni)',
    pa: 'ਕੰਨਿਆ (Kanya)',
    or: 'କନ୍ୟା (Kanya)',
  },
  Libra: {
    en: 'Libra (Tula)',
    hi: 'तुला (Tula)',
    sa: 'तुला (Tulā)',
    gu: 'તુલા (Tula)',
    mr: 'तूळ (Tula)',
    bn: 'তুলা (Tula)',
    ta: 'துலாம் (Thulam)',
    te: 'తుల (Tula)',
    kn: 'ತುಲಾ (Tula)',
    ml: 'തുലാം (Thulam)',
    pa: 'ਤੁਲਾ (Tula)',
    or: 'ତୁଳା (Tula)',
  },
  Scorpio: {
    en: 'Scorpio (Vrischika)',
    hi: 'वृश्चिक (Vrishchik)',
    sa: 'वृश्चिकः (Vṛścika)',
    gu: 'વૃશ્ચિક (Vrushchik)',
    mr: 'वृश्चिक (Vrushchik)',
    bn: 'বৃশ্চিক (Brishchik)',
    ta: 'விருச்சிகம் (Viruchigam)',
    te: 'వృశ్చికం (Vrischikam)',
    kn: 'ವೃಶ್ಚಿಕ (Vrischika)',
    ml: 'വൃശ്ചികം (Vrischikam)',
    pa: 'ਬ੍ਰਿਸ਼ਚਕ (Brishchak)',
    or: 'ବିଛା / ବିଛା (Bichha)',
  },
  Sagittarius: {
    en: 'Sagittarius (Dhanu)',
    hi: 'धनु (Dhanu)',
    sa: 'धनुः (Dhanuḥ)',
    gu: 'ધન (Dhanu)',
    mr: 'धनु (Dhanu)',
    bn: 'ধনু (Dhonu)',
    ta: 'தனுசு (Dhanusu)',
    te: 'ధనుస్సు (Dhanussu)',
    kn: 'ಧನು (Dhanu)',
    ml: 'ധനു (Dhanu)',
    pa: 'ਧਨੁ (Dhanu)',
    or: 'ଧନୁ (Dhanu)',
  },
  Capricorn: {
    en: 'Capricorn (Makara)',
    hi: 'मकर (Makar)',
    sa: 'मकरः (Makara)',
    gu: 'મકર (Makar)',
    mr: 'मकर (Makar)',
    bn: 'মকর (Mokor)',
    ta: 'மகரம் (Magaram)',
    te: 'మకరం (Makaram)',
    kn: 'ಮಕರ (Makara)',
    ml: 'മകരം (Makaram)',
    pa: 'ਮਕਰ (Makar)',
    or: 'ମକର (Makara)',
  },
  Aquarius: {
    en: 'Aquarius (Kumbha)',
    hi: 'कुंभ (Kumbh)',
    sa: 'कुम्भः (Kumbha)',
    gu: 'કુંભ (Kumbh)',
    mr: 'कुंभ (Kumbh)',
    bn: 'কুম্ভ (Kumbho)',
    ta: 'கும்பம் (Kumbam)',
    te: 'కుంభం (Kumbham)',
    kn: 'ಕುಂಭ (Kumbha)',
    ml: 'കുംഭം (Kumbham)',
    pa: 'ਕੁੰਭ (Kumbh)',
    or: 'କୁମ୍ଭ (Kumbha)',
  },
  Pisces: {
    en: 'Pisces (Meena)',
    hi: 'मीन (Meen)',
    sa: 'मीनः (Mīna)',
    gu: 'મીન (Meen)',
    mr: 'मीन (Meen)',
    bn: 'মীন (Meen)',
    ta: 'மீனம் (Meenam)',
    te: 'మీనం (Meenam)',
    kn: 'ಮೀನ (Meena)',
    ml: 'മീനം (Meenam)',
    pa: 'ਮੀਨ (Meen)',
    or: 'ମୀନ (Meena)',
  },
};

// Vedic Gemstone Names
export const GEMSTONE_TRANSLATIONS: Record<string, Record<LanguageCode, string>> = {
  Ruby: {
    en: 'Ruby (Manikya)',
    hi: 'माणिक्य (Manik)',
    sa: 'माणिक्यम् (Māṇikyam)',
    gu: 'માણેક (Manek)',
    mr: 'माणिक (Manik)',
    bn: 'চুনি / মাণিক্য (Chuni/Manik)',
    ta: 'மாணிக்கம் (Manikkam)',
    te: 'మాణిక్యం (Manikyam)',
    kn: 'ಮಾಣಿಕ್ಯ (Manikya)',
    ml: 'മാണിക്യം (Manikyam)',
    pa: 'ਮਾਣਕ (Maanak)',
    or: 'ମାଣିକ୍ୟ (Manikya)',
  },
  Pearl: {
    en: 'Pearl (Moti)',
    hi: 'मोती (Moti)',
    sa: 'मुक्ता (Muktā)',
    gu: 'મોતી (Moti)',
    mr: 'मोती (Moti)',
    bn: 'মুক্তা (Mukta)',
    ta: 'முத்து (Muthu)',
    te: 'ముత్యం (Muthyam)',
    kn: 'ಮುತ್ತು (Muttu)',
    ml: 'മുത്ത് (Muthu)',
    pa: 'ਮੋਤੀ (Moti)',
    or: 'ମୁକ୍ତା (Mukta)',
  },
  'Red Coral': {
    en: 'Red Coral (Moonga)',
    hi: 'मूंगा / प्रवाल (Moonga)',
    sa: 'प्रवालम् (Pravālam)',
    gu: 'પરવાળું (Parwalu)',
    mr: 'पोवळे (Povala)',
    bn: 'পলা / প্রবাল (Pola)',
    ta: 'பவழம் (Pavazham)',
    te: 'పగడం (Pagadam)',
    kn: 'ಹವಳ (Havala)',
    ml: 'പവിഴം (Pavizham)',
    pa: 'ਮੂੰਗਾ (Moonga)',
    or: 'ପୋହଳା (Pohala)',
  },
  Emerald: {
    en: 'Emerald (Panna)',
    hi: 'पन्ना / मरकत (Panna)',
    sa: 'मरकतम् (Marakatam)',
    gu: 'પન્ના (Panna)',
    mr: 'पाचू (Pachoo)',
    bn: 'পান্না (Panna)',
    ta: 'மரகதம் (Maragatham)',
    te: 'మరకతం / పచ్చ (Pachha)',
    kn: 'ಪಚ್ಚೆ (Pachhe)',
    ml: 'മരതകം (Marathakam)',
    pa: 'ਪੰਨਾ (Panna)',
    or: 'ପାନ୍ନା (Panna)',
  },
  'Yellow Sapphire': {
    en: 'Yellow Sapphire (Pukhraj)',
    hi: 'पुखराज / पुष्पराग (Pukhraj)',
    sa: 'पुष्परागम् (Puṣparāgam)',
    gu: 'પોખરાજ (Pokhraj)',
    mr: 'पुष्कराज (Pushkaraj)',
    bn: 'পোখরাজ (Pokhraj)',
    ta: 'புஷ்பராகம் (Pushparagam)',
    te: 'పుష్యరాగం (Pushyaragam)',
    kn: 'ಪುಷ್ಯರಾಗ (Pushyaraga)',
    ml: 'പുഷ്യരാഗം (Pushyaragam)',
    pa: 'ਪੁਖਰਾਜ (Pukhraj)',
    or: 'ପୋଖରାଜ (Pokharaj)',
  },
  Diamond: {
    en: 'Diamond (Heera)',
    hi: 'हीरा / वज्र (Heera)',
    sa: 'वज्रम् (Vajram)',
    gu: 'હીરો (Heero)',
    mr: 'हिरा (Hira)',
    bn: 'হীরা (Heera)',
    ta: 'வைரம் (Vairam)',
    te: 'వజ్రం (Vajram)',
    kn: 'ವಜ್ರ (Vajra)',
    ml: 'വൈരം (Vairam)',
    pa: 'ਹੀਰਾ (Heera)',
    or: 'ହୀରା (Heera)',
  },
  'Blue Sapphire': {
    en: 'Blue Sapphire (Neelam)',
    hi: 'नीलम / इन्द्रनील (Neelam)',
    sa: 'नीलमणिः (Nīlamaṇi)',
    gu: 'નીલમ (Neelam)',
    mr: 'नीलम (Neelam)',
    bn: 'নীলা (Neela)',
    ta: 'நீலக்கல்லு (Neelam)',
    te: 'నీలం (Neelam)',
    kn: 'ನೀಲಮಣಿ (Neelamani)',
    ml: 'ഇന്ദ്രനീലക്കല്ല് (Indraneelam)',
    pa: 'ਨੀਲਮ (Neelam)',
    or: 'ନୀଳମଣି (Neelamani)',
  },
  Hessonite: {
    en: 'Hessonite Garnet (Gomed)',
    hi: 'गोमेद (Gomed)',
    sa: 'गोमेदकम् (Gomedakam)',
    gu: 'ગોમેદ (Gomed)',
    mr: 'गोमेद (Gomed)',
    bn: 'গোমেদ (Gomed)',
    ta: 'கோமேதகம் (Gomedhagam)',
    te: 'గోమేధికం (Gomedhikam)',
    kn: 'ಗೋಮೇಧಿಕ (Gomedhika)',
    ml: 'ഗോമേദകം (Gomedhakam)',
    pa: 'ਗੋਮੇਦ (Gomed)',
    or: 'ଗୋମେଦ (Gomeda)',
  },
  "Cat's Eye": {
    en: "Cat's Eye (Vaidurya / Lahsunia)",
    hi: 'लहसुनिया / वैदूर्य (Lahsunia)',
    sa: 'वैदूर्यम् (Vaidūryam)',
    gu: 'લહસુનિયા (Lahsuniya)',
    mr: 'लसण्या (Lasanya)',
    bn: 'ক্যাটস আই / বৈদূর্য (Vaidurya)',
    ta: 'வைடூரியம் (Vaiduriyam)',
    te: 'వైడూర్యం (Vaiduryam)',
    kn: 'ವೈಡೂರ್ಯ (Vaidurya)',
    ml: 'വൈഡൂര്യം (Vaidooryam)',
    pa: 'ਲਹਸੁਨੀਆ (Lahsuniya)',
    or: 'ବୈଦୂର୍ଯ୍ୟ (Baidurjya)',
  },
};

// UI and Astrological Translation dictionary
export const UI_TRANSLATIONS: Record<string, Record<LanguageCode, string>> = {
  calculatorTitle: {
    en: 'Public Natal Chart Calculator (Swiss Ephemeris)',
    hi: 'जन्म कुण्डली गणना यंत्र (स्विस एफिमेरिस)',
    sa: 'वैदिक जन्मकुण्डली साधनम् (दृक्सिद्ध)',
    gu: 'સંપૂર્ણ જન્મ કુંડળી ગણતરી (સ્વિસ એફિમેરિસ)',
    mr: 'अचूक जन्म पत्रिका व कुंडली कॅल्क्युलेटर',
    bn: 'সঠিক জন্ম কুণ্ডলী ক্যালকুলেটর (স্বিস এফিমেরিস)',
    ta: 'துல்லியமான ஜாதகக் கணிப்பு (சுவிஸ் எபிமெரிஸ்)',
    te: 'ఖచ్చితమైన జాతక చక్ర గణన యంత్రం',
    kn: 'ನಿಖರವಾದ ಜನ್ಮ ಕುಂಡಲಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    ml: 'കൃത്യമായ ജാതക ഗണനയന്ത്രം (സ്വിസ്സ് എഫിമെറിസ്)',
    pa: 'ਅਸਲੀ ਜਨਮ ਕੁੰਡਲੀ ਕੈਲਕੁਲੇਟਰ',
    or: 'ସଠିକ୍ ଜନ୍ମ କୁଣ୍ଡଳୀ ଗଣନା ଯନ୍ତ୍ର',
  },
  calculatorSubtitle: {
    en: 'Calculate precise planetary positions, Ascendant, Midheaven, 12 Houses, and Vedic Gemstone prescriptions.',
    hi: 'सटीक ग्रह स्थिति, लग्न, 12 भाव, और वैदिक रत्न परामर्श की गणना करें।',
    sa: 'स्पष्ट ग्रहस्थितयः, लग्नम्, द्वादशभावाः, तथा च रत्नपरामर्शः।',
    gu: 'ચોક્કસ ગ્રહ સ્થિતિ, લગ્ન, ૧૨ ભાવો અને વૈદિક રત્ન ઉપાય ગણો.',
    mr: 'अचूक ग्रह स्थिती, लग्न, १२ भाव आणि योग्य रत्न मार्गदर्शन मिळवा.',
    bn: 'সঠিক গ্রহের অবস্থান, লগ্ন, ১২টি ভাব এবং রত্ন পরামর্শ নির্ণয় করুন।',
    ta: 'துல்லியமான கிரக நிலைகள், லக்னம், 12 பாவங்கள் மற்றும் நவரத்தின பரிகாரங்கள்.',
    te: 'ఖచ్చితమైన గ్రహ స్థితులు, లగ్నం, 12 భావాలు మరియు రత్న ధారణ సూచనలు.',
    kn: 'ನಿಖರವಾದ ಗ್ರಹ ಸ್ಥಿತಿ, ಲಗ್ನ, 12 ಭಾವಗಳು ಮತ್ತು ವೈದಿಕ ರತ್ನ ಸಲಹೆಗಳು.',
    ml: 'കൃത്യമായ ഗ്രഹനില, ലഗ്നം, 12 ഭാവങ്ങൾ, നവരത്ന നിർദ്ദേശങ്ങൾ എന്നിവ ഗണിക്കുക.',
    pa: 'ਸਹੀ ਗ੍ਰਹਿ ਸਥਿਤੀ, ਲਗਨ, 12 ਭਾਵ ਅਤੇ ਰਤਨ ਉਪਾਅ ਵੇਖੋ।',
    or: 'ସଠିକ୍ ଗ୍ରହ ସ୍ଥିତି, ଲଗ୍ନ, ୧୨ ଭାବ ଏବଂ ବୈଦିକ ରତ୍ନ ପରାମର୍ଶ ଗଣନା କରନ୍ତୁ।',
  },
  subjectName: {
    en: 'Subject Name',
    hi: 'जातक का नाम (Subject Name)',
    sa: 'जातकस्य नाम',
    gu: 'જાતકનું નામ (Subject Name)',
    mr: 'जातकाचे नाव (Subject Name)',
    bn: 'জাতকের নাম',
    ta: 'ஜாதகர் பெயர்',
    te: 'జాతకుని పేరు',
    kn: 'ಜಾತಕರ ಹೆಸರು',
    ml: 'ജാതകന്റെ പേര്',
    pa: 'ਵਿਅਕਤੀ ਦਾ ਨਾਮ',
    or: 'ଜାତକଙ୍କ ନାମ',
  },
  dateOfBirth: {
    en: 'Date of Birth',
    hi: 'जन्म तिथि (Date of Birth)',
    sa: 'जन्मदिनाङ्कः',
    gu: 'જન્મ તારીખ',
    mr: 'जन्मतारीख',
    bn: 'জন্ম তারিখ',
    ta: 'பிறந்த தேதி',
    te: 'పుట్టిన తేదీ',
    kn: 'ಹುಟ್ಟಿದ ದಿನಾಂಕ',
    ml: 'ജനന തീയതി',
    pa: 'ਜਨਮ ਮਿਤੀ',
    or: 'ଜନ୍ମ ତାରିଖ',
  },
  timeOfBirth: {
    en: 'Time of Birth (Exact)',
    hi: 'जन्म समय (सटीक)',
    sa: 'जन्मसमयः (स्पष्टः)',
    gu: 'જન્મ સમય (ચોક્કસ)',
    mr: 'जन्म वेळ (अचूक)',
    bn: 'জন্মের সঠিক সময়',
    ta: 'பிறந்த நேரம் (துல்லியமாக)',
    te: 'పుట్టిన సమయం (ఖచ్చితంగా)',
    kn: 'ಹುಟ್ಟಿದ ಸಮಯ (ನಿಖರ)',
    ml: 'ജനന സമയം (കൃത്യമായി)',
    pa: 'ਜਨਮ ਸਮਾਂ (ਸਹੀ)',
    or: 'ଜନ୍ମ ସମୟ (ସଠିକ୍)',
  },
  placeOfBirth: {
    en: 'Place of Birth (City)',
    hi: 'जन्म स्थान (शहर)',
    sa: 'जन्मस्थानम् (नगरम्)',
    gu: 'જન્મ સ્થળ (શહેર)',
    mr: 'जन्मस्थान (गाव/शहर)',
    bn: 'জন্মস্থান (শহর)',
    ta: 'பிறந்த இடம் (ஊர்/நகரம்)',
    te: 'పుట్టిన ప్రదేశం (నగరం)',
    kn: 'ಹುಟ್ಟಿದ ಸ್ಥಳ (ನಗರ)',
    ml: 'ജനിച്ച സ്ഥലം (നഗരം)',
    pa: 'ਜਨਮ ਸਥਾਨ (ਸ਼ਹਿਰ)',
    or: 'ଜନ୍ମ ସ୍ଥାନ (ସହର)',
  },
  calculateButton: {
    en: 'Calculate Ephemeris Chart',
    hi: 'जन्म कुण्डली बनाएं (Calculate Chart)',
    sa: 'कुण्डलीं निर्मातु',
    gu: 'કુંડળી ગણો (Calculate Chart)',
    mr: 'पत्रिका तयार करा (Calculate)',
    bn: 'কুণ্ডলী তৈরি করুন',
    ta: 'ஜாதகம் கணிக்கவும்',
    te: 'జాతక చక్రాన్ని లెక్కించండి',
    kn: 'ಕುಂಡಲಿ ಲೆಕ್ಕ ಹಾಕಿ',
    ml: 'ജാതകം ഗണിക്കുക',
    pa: 'ਕੁੰਡਲੀ ਬਣਾਓ',
    or: 'ଜନ୍ମ କୁଣ୍ଡଳୀ ଗଣନା କରନ୍ତୁ',
  },
  calculating: {
    en: 'Computing Swiss Ephemeris...',
    hi: 'ग्रहों की गणना हो रही है...',
    sa: 'ग्रहस्पष्टीकरणं प्रचलति...',
    gu: 'ગ્રહોની ગણતરી ચાલુ છે...',
    mr: 'अचूक ग्रहस्थिती गणत आहे...',
    bn: 'গ্রহের অবস্থান গণনা করা হচ্ছে...',
    ta: 'கிரக நிலைகள் கணிக்கப்படுகின்றன...',
    te: 'గ్రహ స్థితులు గణింపబడుతున్నాయి...',
    kn: 'ಗ್ರಹಗಳ ಲೆಕ್ಕಾಚಾರ ನಡೆಯುತ್ತಿದೆ...',
    ml: 'ഗ്രഹങ്ങൾ കണക്കാക്കുന്നു...',
    pa: 'ਕੁੰਡਲੀ ਦੀ ਗਣਨਾ ਹੋ ਰਹੀ ਹੈ...',
    or: 'ଗ୍ରହ ସ୍ଥିତି ଗଣନା ଚାଲିଛି...',
  },
  quickSamples: {
    en: 'Quick Samples',
    hi: 'त्वरित उदाहरण (Quick Samples)',
    sa: 'शीघ्रोदाहरणानि',
    gu: 'ઝડપી ઉદાહરણો',
    mr: 'नमुना प्रोफाईल',
    bn: 'দ্রুত উদাহরণ',
    ta: 'மாதிரி அமைப்புகள்',
    te: 'శీఘ్ర నమూనాలు',
    kn: 'ಮಾದರಿಗಳು',
    ml: 'മാതൃകകൾ',
    pa: 'ਨਮੂਨੇ',
    or: 'ଉଦାହରଣ',
  },
  selectLanguage: {
    en: 'Indian Language',
    hi: 'भाषा चुनें (Select Language)',
    sa: 'भाषां चिनोतु',
    gu: 'ભાષા પસંદ કરો',
    mr: 'भाषा निवडा',
    bn: 'ভাষা নির্বাচন করুন',
    ta: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    te: 'భాషను ఎంచుకోండి',
    kn: 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    ml: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    pa: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    or: 'ଭାଷା ବାଛନ୍ତୁ',
  },
  planetaryPositions: {
    en: 'Planetary Positions & Dignities',
    hi: 'ग्रह स्थिति और बल (Planetary Positions & Dignities)',
    sa: 'ग्रहस्थितयः तथा बलम्',
    gu: 'ગ્રહ સ્થિતિ અને બળ',
    mr: 'ग्रह स्थिती व ग्रहबल',
    bn: 'গ্রহের অবস্থান ও বল',
    ta: 'கிரக நிலைகளும் பலங்களும்',
    te: 'గ్రహ స్థితులు మరియు బలములు',
    kn: 'ಗ್ರಹ ಸ್ಥಿತಿಗಳು ಮತ್ತು ಬಲಗಳು',
    ml: 'ഗ്രഹ നിലകളും ബലങ്ങളും',
    pa: 'ਗ੍ਰਹਿ ਸਥਿਤੀ ਅਤੇ ਬਲ',
    or: 'ଗ୍ରହ ସ୍ଥିତି ଏବଂ ବଳ',
  },
  gemstonePrescription: {
    en: 'Jyotish Gemstone Prescription (Ratna Chikitsa)',
    hi: 'ज्योतिषीय रत्न परामर्श (रत्न चिकित्सा)',
    sa: 'ज्योतिषीय रत्नपरामर्शः (रत्नचिकित्सा)',
    gu: 'જ્યોતિષીય રત્ન ઉપાય (રત્ન ચિકિત્સા)',
    mr: 'ज्योतिषीय रत्न सल्ला (रत्न चिकित्सा)',
    bn: 'জ্যোতিষীয় রত্ন প্রেসক্রিপশন (রত্ন চিকিৎসা)',
    ta: 'ஜோதிட ரத்தினப் பரிந்துரை (ரத்ன பரிகாரம்)',
    te: 'జ్యోతిష్య రత్న ధారణ సలహా (రత్న చికిత్స)',
    kn: 'ಜ್ಯೋತಿಷ್ಯ ರತ್ನ ಸಲಹೆ (ರತ್ನ ಚಿಕಿತ್ಸೆ)',
    ml: 'ജ്യോതിഷ രത്ന നിർദ്ദേശം (രത്ന ചികിത്സ)',
    pa: 'ਜੋਤਿਸ਼ ਰਤਨ ਉਪਾਅ',
    or: 'ଜ୍ୟୋତିଷ ରତ୍ନ ପରାମର୍ଶ (ରତ୍ନ ଚିକିତ୍ସା)',
  },
  lifeStone: {
    en: 'Life Stone (Lagna Lord)',
    hi: 'जीवन रत्न (लग्नेश)',
    sa: 'जीवनरत्नम् (लग्नेशः)',
    gu: 'જીવન રત્ન (લગ્નેશ)',
    mr: 'जीवन रत्न (लग्नेश)',
    bn: 'জীবন রত্ন (লগ্নপতি)',
    ta: 'ஜீவ ரத்தினம் (லக்னாதிபதி)',
    te: 'జీవ రత్నం (లగ్నాధిపతి)',
    kn: 'ಜೀವ ರತ್ನ (ಲಗ್ನಾಧಿಪತಿ)',
    ml: 'ജീവ രത്നം (ലഗ്നാധിപൻ)',
    pa: 'ਜੀਵਨ ਰਤਨ (ਲਗਨੇਸ਼)',
    or: 'ଜୀବନ ରତ୍ନ (ଲଗ୍ନେଶ)',
  },
  luckyStone: {
    en: 'Lucky Stone (Bhagya Lord)',
    hi: 'भाग्य रत्न (नवमेश)',
    sa: 'भाrunning्यरत्नम् (भाग्येशः)',
    gu: 'ભાગ્ય રત્ન (ભાગ્યેશ)',
    mr: 'भाग्य रत्न (नवमेश)',
    bn: 'ভাগ্য রত্ন (ভাগ্যপতি)',
    ta: 'பாக்கிய ரத்தினம் (பாக்கியாதிபதி)',
    te: 'భాగ్య రత్నం (భాగ్యాధిపతి)',
    kn: 'ಭಾಗ್ಯ ರತ್ನ (ಭಾಗ್ಯಾಧಿಪತಿ)',
    ml: 'ഭാഗ്യ രത്നം (ഭാഗ്യാധിപൻ)',
    pa: 'ਭਾਗ ਰਤਨ (ਭਾਗਿਆਪਤੀ)',
    or: 'ଭାଗ୍ୟ ରତ୍ନ (ଭାଗ୍ୟେଶ)',
  },
  fortuneStone: {
    en: 'Fortune / Intellect Stone (5th Lord)',
    hi: 'संतान व विद्या रत्न (पंचमेश)',
    sa: 'विद्यारत्नम् (पञ्चमेशः)',
    gu: 'વિદ્યા અને પુણ્ય રત્ન (પંચમેશ)',
    mr: 'पुण्य व विद्या रत्न (पंचमेश)',
    bn: 'বিদ্যারত্ন (পঞ্চমপতি)',
    ta: 'புண்ணிய ரத்தினம் (பஞ்சமாதிபதி)',
    te: 'విద్యా రత్నం (పంచమాధిపతి)',
    kn: 'ವಿದ್ಯಾ ರತ್ನ (ಪಂಚಮಾಧಿಪತಿ)',
    ml: 'വിദ്യാ രത്നം (പഞ്ചമാധിപൻ)',
    pa: 'ਵਿੱਦਿਆ ਰਤਨ (ਪੰਚਮੇਸ਼)',
    or: 'ବିଦ୍ୟା ରତ୍ନ (ପଞ୍ଚମେଶ)',
  },
  prescribedWeight: {
    en: 'Prescribed Weight',
    hi: 'उचित वजन (रत्ती / कैरेट)',
    sa: 'निर्धारितभारः (रत्तिका)',
    gu: 'યોગ્ય વજન (રત્તી/કેરેટ)',
    mr: 'योग्य वजन (रत्ती/कॅरेट)',
    bn: 'উপযুক্ত ওজন (রত্তি/ক্যারেট)',
    ta: 'பரிந்துரைக்கப்பட்ட எடை (ரத்தி/காரட்)',
    te: 'సిఫార్సు చేసిన బరువు (రత్తి/క్యారెట్)',
    kn: 'ಸೂಚಿಸಿದ ತೂಕ (ರತ್ತಿ/ಕ್ಯಾರೆಟ್)',
    ml: 'നിർദ്ദേശിച്ച ഭാരം (രത്തി/കാരറ്റ്)',
    pa: 'ਸਹੀ ਭਾਰ (ਰੱਤੀ/ਕੈਰੇਟ)',
    or: 'ସଠିକ୍ ଓଜନ (ରତ୍ତି/କ୍ୟାରେଟ୍)',
  },
  recommendedMetal: {
    en: 'Recommended Metal',
    hi: 'धारण हेतु धातु',
    sa: 'धार्यधातुः',
    gu: 'ધારણ કરવાની ધાતુ',
    mr: 'वापरण्याची धातू',
    bn: 'ব্যবহার্য ধাতু',
    ta: 'பயன்படுத்த வேண்டிய உலோகம்',
    te: 'ధరించవలసిన లోహం',
    kn: 'ಧರಿಸಬೇಕಾದ ಲೋಹ',
    ml: 'ധരിക്കേണ്ട ലോഹം',
    pa: 'ਪਹਿਨਣ ਲਈ ਧਾਤੂ',
    or: 'ଧାରଣ ପାଇଁ ଧାତୁ',
  },
  auspiciousFinger: {
    en: 'Auspicious Finger',
    hi: 'धारण करने की अंगुली',
    sa: 'धार्याङ्गुलिः',
    gu: 'ધારણ કરવાની આંગળી',
    mr: 'धारण करावयाचे बोट',
    bn: 'আংটি পরার আঙুল',
    ta: 'மோதிரம் அணிய வேண்டிய விரல்',
    te: 'ధరించవలసిన వేలు',
    kn: 'ಧರಿಸಬೇಕಾದ ಬೆರಳು',
    ml: 'മോതിരം ധരിക്കേണ്ട വിരൽ',
    pa: 'ਪਹਿਨਣ ਵਾਲੀ ਉਂਗਲ',
    or: 'ଧାରଣ କରିବା ଆଙ୍ଗୁଳି',
  },
  chantMantra: {
    en: 'Activation Mantra',
    hi: 'जाप मंत्र (Graha Mantra)',
    sa: 'ग्रहबीजमन्त्रः',
    gu: 'ગ્રહ જાપ મંત્ર',
    mr: 'ग्रह बीजमंत्र',
    bn: 'গ্রহ জপ মন্ত্র',
    ta: 'கிரக மந்திரம்',
    te: 'గ్రహ జప మంత్రం',
    kn: 'ಗ್ರಹ ಜಪ ಮಂತ್ರ',
    ml: 'ഗ്രഹ മന്ത്രം',
    pa: 'ਗ੍ਰਹਿ ਮੰਤਰ',
    or: 'ଗ୍ରହ ମନ୍ତ୍ର',
  },
  saveToCRM: {
    en: 'Save Chart to Back-Office CRM',
    hi: 'कुण्डली को CRM में सुरक्षित करें',
    sa: 'कुण्डलीं कोशे संरक्षतु',
    gu: 'કુંડળીને CRM મા સાચવો',
    mr: 'कुंडली CRM मध्ये सेव्ह करा',
    bn: 'কুণ্ডলী CRM-এ সংরক্ষণ করুন',
    ta: 'ஜாதகத்தை CRM-ல் சேமிக்கவும்',
    te: 'జాతకాన్ని CRM లో భద్రపరచండి',
    kn: 'ಕುಂಡಲಿಯನ್ನು CRM ನಲ್ಲಿ ಉಳಿಸಿ',
    ml: 'ജാതകം CRM-ൽ സൂക്ഷിക്കുക',
    pa: 'ਕੁੰਡਲੀ ਨੂੰ CRM ਵਿੱਚ ਸੰਭਾਲੋ',
    or: 'କୁଣ୍ଡଳୀକୁ CRM ରେ ସଂରକ୍ଷଣ କରନ୍ତୁ',
  },
  downloadPDF: {
    en: 'Download PDF Report',
    hi: 'PDF रिपोर्ट डाउनलोड करें',
    sa: 'PDF पत्रं डाउनलोड कुर्वन्तु',
    gu: 'PDF રિપોર્ટ ડાઉનલોડ કરો',
    mr: 'PDF अहवाल डाउनलोड करा',
    bn: 'PDF রিপোর্ট ডাউনলোড করুন',
    ta: 'PDF அறிக்கையைப் பதிவிறக்கவும்',
    te: 'PDF నివేదికను డౌన్‌లోడ్ చేయండి',
    kn: 'PDF ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    ml: 'PDF റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    pa: 'PDF ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ',
    or: 'PDF ରିପୋର୍ଟ ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
  },
  printReport: {
    en: 'Print Kundali / Chart',
    hi: 'कुण्डली प्रिंट करें (Print)',
    sa: 'कुण्डलीं मुद्रयतु',
    gu: 'કુંડળી પ્રિન્ટ કરો',
    mr: 'पत्रिका प्रिंट करा',
    bn: 'কুণ্ডলী প্রিন্ট করুন',
    ta: 'ஜாதகத்தை அச்சிடுக',
    te: 'జాతకాన్ని ప్రింట్ చేయండి',
    kn: 'ಕುಂಡಲಿ ಮುದ್ರಿಸಿ',
    ml: 'ജാതകം പ്രിന്റ് ചെയ്യുക',
    pa: 'ਕੁੰਡਲੀ ਪ੍ਰਿੰਟ ਕਰੋ',
    or: 'କୁଣ୍ଡଳୀ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
  },
  direct: {
    en: 'Direct (Margi)',
    hi: 'मार्गी (Direct)',
    sa: 'मार्गी',
    gu: 'માર્ગી',
    mr: 'मार्गी',
    bn: 'মার্গী',
    ta: 'நேர்கதி (Margi)',
    te: 'ఋజుగతి (Margi)',
    kn: 'ನೇರ ಗತಿ (Margi)',
    ml: 'നേർഗതി (Margi)',
    pa: 'ਮਾਰਗੀ',
    or: 'ମାର୍ଗୀ',
  },
  retrograde: {
    en: 'Retrograde (Vakri)',
    hi: 'वक्री (Rx)',
    sa: 'वक्री (Vakrī)',
    gu: 'વક્રી (Rx)',
    mr: 'वक्री (Rx)',
    bn: 'বক্রী (Rx)',
    ta: 'வக்ரம் (Rx)',
    te: 'వక్రగతి (Rx)',
    kn: 'ವಕ್ರ ಗತಿ (Rx)',
    ml: 'വക്രഗതി (Rx)',
    pa: 'ਵਕਰੀ (Rx)',
    or: 'ବକ୍ରୀ (Rx)',
  },
  house: {
    en: 'House / Bhava',
    hi: 'भाव (House)',
    sa: 'भावः',
    gu: 'ભાવ (House)',
    mr: 'भाव / स्थान',
    bn: 'ভাব (House)',
    ta: 'பாவம் (House)',
    te: 'భావము (House)',
    kn: 'ಭಾವ (House)',
    ml: 'ഭാവം (House)',
    pa: 'ਘਰ / ਭਾਵ',
    or: 'ଭାବ (House)',
  },
  predictionsTitle: {
    en: 'Astrological Predictions & Forecast (भविष्यफल)',
    hi: 'साप्ताहिक, मासिक एवं वार्षिक भविष्यफल (Predictions)',
    sa: 'कालचक्रफलम् (साप्ताहिक-मासिक-वार्षिकफलम्)',
    gu: 'સાપ્તાહિક, માસિક અને વાર્ષિક રાશિફળ',
    mr: 'साप्ताहिक, मासिक आणि वार्षिक भविष्यफल',
    bn: 'সাপ্তাহিক, মাসিক ও বার্ষিক রাশিফল',
    ta: 'வாராந்திர, மாதாந்திர மற்றும் வருடாந்திர பலன்கள்',
    te: 'వార, మాస మరియు వార్షిక జాతక ఫలితాలు',
    kn: 'ವಾರದ, ಮಾಸಿಕ ಮತ್ತು ವಾರ್ಷಿಕ ಭವಿಷ್ಯಫಲ',
    ml: 'പ്രവചനങ്ങളും ജാതകഫലങ്ങളും (വാരാന്ത്യ/മാസിക/വാർഷിക)',
    pa: 'ਹਫ਼ਤਾਵਾਰੀ, ਮਹੀਨਾਵਾਰ ਅਤੇ ਸਾਲਾਨਾ ਭਵਿੱਖਬਾਣੀ',
    or: 'ସାପ୍ତାହିକ, ମାସିକ ଓ ବାର୍ଷିକ ରାଶିଫଳ',
  },
  predictionsSubtitle: {
    en: 'Easy-to-understand life forecasts tailored to your natal chart and planetary transits (Gochara).',
    hi: 'आपकी जन्म कुण्डली एवं गोचर के आधार पर सरल व व्यावहारिक जीवन मार्गदर्शन।',
    sa: 'गोचरग्रहस्थित्याधारितं सरलजीवनमार्गदर्शनम्।',
    gu: 'તમારી જન્મકુંડળી અને ગ્રહ ગોચર આધારિત સરળ જીવન માર્ગદર્શન.',
    mr: 'तुमच्या जन्मकुंडली व गोचर ग्रहांवर आधारित सुलभ व व्यवहारी मार्गदर्शन.',
    bn: 'আপনার জন্মছক ও গ্রহ গোচরের ওপর ভিত্তি করে সহজ জীবন পূর্বাভাস।',
    ta: 'உங்கள் ஜாதகம் மற்றும் கிரகப் பெயர்ச்சி அடிப்படையிலான எளிய பலன்கள்.',
    te: 'మీ జాతక చక్రం మరియు గ్రహ గోచారం ఆధారంగా సులభమైన జీవిత ఫలితాలు.',
    kn: 'ನಿಮ್ಮ ಜನ್ಮ ಕುಂಡಲಿ ಮತ್ತು ಗ್ರಹ ಗೋಚಾರದ ಆಧಾರದ ಸರಳ ಜೀವನ ಭವಿಷ್ಯ.',
    ml: 'നിങ്ങളുടെ ജാതകവും ഗ്രഹസ്ഥിതിയും അടിസ്ഥാനമാക്കിയുള്ള ലളിതമായ പ്രവചനം.',
    pa: 'ਤੁਹਾਡੀ ਜਨਮ ਕੁੰਡਲੀ ਅਤੇ ਗ੍ਰਹਿਆਂ ਦੇ ਗੋਚਰ ਅਨੁਸਾਰ ਸਰਲ ਜੀਵਨ ਅਗਵਾਈ।',
    or: 'ଆପଣଙ୍କ ଜନ୍ମ କୁଣ୍ଡଳୀ ଓ ଗ୍ରହ ଗୋଚର ଉପରେ ଆଧାରିତ ସରଳ ଭବିଷ୍ୟଫଳ।',
  },
  weeklyForecast: {
    en: 'Weekly Forecast (साप्ताहिक)',
    hi: 'साप्ताहिक भविष्यफल (Weekly)',
    sa: 'साप्ताहिकफलम्',
    gu: 'સાપ્તાહિક રાશિફળ',
    mr: 'साप्ताहिक भविष्य',
    bn: 'সাপ্তাহিক রাশিফল',
    ta: 'வார பலன்கள் (Weekly)',
    te: 'వార ఫలితాలు (Weekly)',
    kn: 'ವಾರದ ಭವಿಷ್ಯ (Weekly)',
    ml: 'വാരഫലം (Weekly)',
    pa: 'ਹਫ਼ਤਾਵਾਰੀ ਫਲ',
    or: 'ସାପ୍ତାହିକ ଫଳ',
  },
  monthlyForecast: {
    en: 'Monthly Forecast (मासिक)',
    hi: 'मासिक भविष्यफल (Monthly)',
    sa: 'मासिकफलम्',
    gu: 'માસિક રાશિફળ',
    mr: 'मासिक भविष्य',
    bn: 'মাসিক রাশিফল',
    ta: 'மாத பலன்கள் (Monthly)',
    te: 'మాస ఫలితాలు (Monthly)',
    kn: 'ಮಾಸಿಕ ಭವಿಷ್ಯ (Monthly)',
    ml: 'മാസഫലം (Monthly)',
    pa: 'ਮਹੀਨਾਵਾਰ ਫਲ',
    or: 'ମାସିକ ଫଳ',
  },
  yearlyForecast: {
    en: 'Yearly Forecast (वार्षिक)',
    hi: 'वार्षिक भविष्यफल (Yearly)',
    sa: 'वार्षिकफलम्',
    gu: 'વાર્ષિક રાશિફળ',
    mr: 'वार्षिक भविष्य',
    bn: 'বার্ষিক রাশিফল',
    ta: 'வருட பலன்கள் (Yearly)',
    te: 'వార్షిక ఫలితాలు (Yearly)',
    kn: 'ವಾರ್ಷಿಕ ಭವಿಷ್ಯ (Yearly)',
    ml: 'വാർഷിക ഫലം (Yearly)',
    pa: 'ਸਾਲਾਨਾ ਫਲ',
    or: 'ବାର୍ଷିକ ଫଳ',
  },
  careerAndMoney: {
    en: 'Career, Business & Finances',
    hi: 'करियर, व्यापार व धनलाभ (Career & Wealth)',
    sa: 'कार्यक्षेत्रं वित्तलाभश्च',
    gu: 'કારકિર્દી, વ્યવસાય અને આર્થિક વૃદ્ધિ',
    mr: 'नोकरी, व्यवसाय आणि धनलाभ',
    bn: 'কর্মজীবন, ব্যবসা ও অর্থভাগ্য',
    ta: 'தொழில், வியாபாரம் மற்றும் பணவரவு',
    te: 'వృత్తి, వ్యాపారం మరియు ఆర్థికాభివృద్ధి',
    kn: 'ಉದ್ಯೋಗ, ವ್ಯಾಪಾರ ಮತ್ತು ಧನಲಾಭ',
    ml: 'തൊഴിൽ, ബിസിനസ്സ്, സാമ്പത്തിക ലാഭം',
    pa: 'ਕੰਮਕਾਜ, ਵਪਾਰ ਅਤੇ ਧਨ ਲਾਭ',
    or: 'କର୍ମକ୍ଷେତ୍ର, ବ୍ୟବସାୟ ଓ ଧନଲାଭ',
  },
  loveAndFamily: {
    en: 'Love, Marriage & Family Relations',
    hi: 'प्रेम, वैवाहिक सुख व पारिवारिक संबंध',
    sa: 'स्नेहः, दाम्पत्यं पारिवारिकसुखम्',
    gu: 'પ્રેમ, દાંપત્ય જીવન અને પારિવારિક સુખ',
    mr: 'प्रेम, वैवाहिक जीवन आणि कौटुंबिक सौख्य',
    bn: 'প্রেম, বিবাহ ও পারিবারিক সম্প্রীতি',
    ta: 'அன்பு, திருமணம் மற்றும் குடும்ப உறவுகள்',
    te: 'ప్రేమ, వైవాహిక జీవితం మరియు కుటుంబ బంధాలు',
    kn: 'ಪ್ರೀತಿ, ದಾಂಪತ್ಯ ಮತ್ತು ಕುಟುಂಬ ಸಾಮರಸ್ಯ',
    ml: 'പ്രണയം, ദാമ്പത്യം, കുടുംബബന്ധങ്ങൾ',
    pa: 'ਪਿਆਰ, ਵਿਆਹ ਅਤੇ ਪਰਿਵਾਰਕ ਸਬੰਧ',
    or: 'ପ୍ରେମ, ବିବାହ ଓ ପାରିବାରିକ ସମ୍ପର୍କ',
  },
  healthAndVitality: {
    en: 'Health, Energy & Well-being',
    hi: 'स्वास्थ्य, ऊर्जा व मानसिक शांति (Health)',
    sa: 'आरोग्यं शक्तिः मानसिकशान्तिश्च',
    gu: 'આરોગ્ય, શક્તિ અને માનસિક શાંતિ',
    mr: 'आरोग्य, ऊर्जा आणि मनःशांती',
    bn: 'স্বাস্থ্য, জীবনীশক্তি ও মানসিক শান্তি',
    ta: 'உடல்நலம், புத்துணர்ச்சி மற்றும் மன அமைதி',
    te: 'ఆరోగ్యం, శక్తి మరియు మానసిక ప్రశాంతత',
    kn: 'ಆರೋಗ್ಯ, ಶಕ್ತಿ ಮತ್ತು ಮನಃಶಾಂತಿ',
    ml: 'ആരോഗ്യം, ഊർജ്ജസ്വലത, മാനസിക സുഖം',
    pa: 'ਸਿਹਤ, ਊਰਜਾ ਅਤੇ ਮਾਨਸਿਕ ਸ਼ਾਂਤੀ',
    or: 'ସ୍ୱାସ୍ଥ୍ୟ, ଶକ୍ତି ଓ ମାନସିକ ଶାନ୍ତି',
  },
  favorableActivities: {
    en: 'Favorable Activities (What is Favored)',
    hi: 'अनुकूल कार्य (इस अवधि में क्या करें)',
    sa: 'अनुकूलकार्याणि',
    gu: 'અનુકૂળ કાર્યો (આ સમયમાં શું કરવું)',
    mr: 'अनुकूल कार्ये (काय करावे)',
    bn: 'অনুকূল কাজ (কী করা ভালো)',
    ta: 'செய்ய வேண்டிய நல்ல காரியங்கள்',
    te: 'అనుకూలమైన పనులు (ఏమి చేయాలి)',
    kn: 'ಅನುಕೂಲಕರ ಕಾರ್ಯಗಳು (ಏನು ಮಾಡಬೇಕು)',
    ml: 'അനുകൂലമായ പ്രവൃത്തികൾ (ചെയ്യേണ്ടവ)',
    pa: 'ਚੰਗੇ ਕੰਮ (ਕੀ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ)',
    or: 'ଅନୁକୂଳ କାର୍ଯ୍ୟ (କଣ କରିବା ଉଚିତ)',
  },
  cautionActivities: {
    en: 'Things to Avoid & Precautions',
    hi: 'सावधानियां (क्या न करें / किससे बचें)',
    sa: 'सावधानी / वर्जनीयानि',
    gu: 'સાવચેતી (શું ન કરવું / બચવું)',
    mr: 'सावधानता (काय टाळावे)',
    bn: 'সতর্কতা (কী বর্জন করবেন)',
    ta: 'தவிர்க்க வேண்டியவை மற்றும் எச்சரிக்கைகள்',
    te: 'జాగ్రత్తలు (ఏమి చేయకూడదు)',
    kn: 'ಎಚ್ಚರಿಕೆಗಳು (ಏನು ಮಾಡಬಾರದು)',
    ml: 'ശ്രദ്ധിക്കേണ്ട കാര്യങ്ങൾ (ഒഴിവാക്കേണ്ടവ)',
    pa: 'ਸਾਵਧਾਨੀਆਂ (ਕੀ ਨਾ ਕਰੋ)',
    or: 'ସାବଧାନତା (କଣ କରିବା ଅନୁଚିତ)',
  },
  luckyElements: {
    en: 'Lucky Elements & Daily Guidance',
    hi: 'शुभ तत्व एवं दैनिक मार्गदर्शन (Lucky Elements)',
    sa: 'शुभतत्त्वानि तथा च मार्गदर्शनम्',
    gu: 'શુભ તત્વો અને માર્ગદર્શન',
    mr: 'शुभ घटक आणि मार्गदर्शन',
    bn: 'শুভ উপাদান ও দৈনিক দিকনির্দেশনা',
    ta: 'அதிர்ஷ்டக் கூறுகள் மற்றும் தினசரி வழிகாட்டல்',
    te: 'అదృష్ట అంశాలు మరియు మార్గదర్శకత్వం',
    kn: 'ಶುಭ ಅಂಶಗಳು ಮತ್ತು ಮಾರ್ಗದರ್ಶನ',
    ml: 'ഭാഗ്യ ഘടകങ്ങളും നിർദ്ദേശങ്ങളും',
    pa: 'ਸ਼ੁਭ ਤੱਤ ਅਤੇ ਰੋਜ਼ਾਨਾ ਸੇਧ',
    or: 'ଶୁଭ ଉପାଦାନ ଓ ଦୈନିକ ମାର୍ଗଦର୍ଶନ',
  },
  actionableTip: {
    en: 'Everyday Practical Advice',
    hi: 'दैनिक जीवन के लिए व्यावहारिक सुझाव',
    sa: 'व्यावहारिकः परामर्शः',
    gu: 'રોજિંદા જીવન માટે વ્યવહારુ સલાહ',
    mr: 'दैनंदिन जीवनासाठी मोलाचा सल्ला',
    bn: 'দৈনন্দিন জীবনের কার্যকরী পরামর্শ',
    ta: 'நடைமுறை வாழ்க்கைக் குறிப்பு',
    te: 'నిత్య జీవిత ఆచరణాత్మక సలహా',
    kn: 'ದೈನಂದಿನ ಜೀವನದ ಪ್ರಾಯೋಗಿಕ ಸಲಹೆ',
    ml: 'ദൈനംദിന ജീവിതത്തിനുള്ള ഉപദേശം',
    pa: 'ਰੋਜ਼ਾਨਾ ਜ਼ਿੰਦਗੀ ਲਈ ਲਾਭਦਾਇਕ ਸੁਝਾਅ',
    or: 'ଦୈନନ୍ଦିନ ଜୀବନ ପାଇଁ ବ୍ୟବହାରିକ ପରାମର୍ଶ',
  },
  astrologicalTransits: {
    en: 'Planetary Transits & House Influences (Gochara)',
    hi: 'ग्रह गोचर एवं भाव प्रभाव (Jyotish Basis)',
    sa: 'ग्रहगोचरः भावप्रभवश्च',
    gu: 'ગ્રહ ગોચર અને ભાવ પ્રભાવ',
    mr: 'ग्रह गोचर व भाव प्रभाव',
    bn: 'গ্রহ গোচর ও ভাব প্রভাব',
    ta: 'கிரகப் பெயர்ச்சி மற்றும் பாவ தாக்கங்கள்',
    te: 'గ్రహ గోచారం మరియు భావ ప్రభావాలు',
    kn: 'ಗ್ರಹ ಗೋಚಾರ ಮತ್ತು ಭಾವ ಪ್ರಭಾವಗಳು',
    ml: 'ഗ്രഹ സഞ്ചാരവും ഭാവ സ്വാധീനവും',
    pa: 'ਗ੍ਰਹਿ ਗੋਚਰ ਅਤੇ ਭਾਵ ਪ੍ਰਭਾਵ',
    or: 'ଗ୍ରହ ଗୋଚର ଓ ଭାବ ପ୍ରଭାବ',
  },
};

/**
 * Get translated text helper
 */
export function getTranslation(key: string, lang: LanguageCode | string = 'en'): string {
  const safeLang = (lang as LanguageCode) || 'en';
  if (UI_TRANSLATIONS[key] && UI_TRANSLATIONS[key][safeLang]) {
    return UI_TRANSLATIONS[key][safeLang];
  }
  if (UI_TRANSLATIONS[key] && UI_TRANSLATIONS[key]['en']) {
    return UI_TRANSLATIONS[key]['en'];
  }
  return key;
}

/**
 * Get translated Planet name
 */
export function getPlanetName(planetName: string, lang: LanguageCode | string = 'en'): string {
  const safeLang = (lang as LanguageCode) || 'en';
  if (PLANET_TRANSLATIONS[planetName] && PLANET_TRANSLATIONS[planetName][safeLang]) {
    return PLANET_TRANSLATIONS[planetName][safeLang];
  }
  return planetName;
}

/**
 * Get translated Zodiac Sign name
 */
export function getSignName(signName: string, lang: LanguageCode | string = 'en'): string {
  const safeLang = (lang as LanguageCode) || 'en';
  if (SIGN_TRANSLATIONS[signName] && SIGN_TRANSLATIONS[signName][safeLang]) {
    return SIGN_TRANSLATIONS[signName][safeLang];
  }
  return signName;
}

/**
 * Get translated Gemstone name
 */
export function getGemstoneName(gemstoneName: string, lang: LanguageCode | string = 'en'): string {
  const safeLang = (lang as LanguageCode) || 'en';
  if (GEMSTONE_TRANSLATIONS[gemstoneName] && GEMSTONE_TRANSLATIONS[gemstoneName][safeLang]) {
    return GEMSTONE_TRANSLATIONS[gemstoneName][safeLang];
  }
  return gemstoneName;
}
